### ISSUE TITLE
Docker error - probably Nipype related

### ISSUE THREAD

**Issue by malywladek** [FCP-INDI/C-PAC#1006]
I just wanted to test C-PAC in Docker (latest ver. 1.4.3). I have simple data structure with T1w and 300 volumes of rest. In standard pipeline with map disabled i get following crash error:

`nipypecli crash crash-20190603-105913-root-check_func_scan.b0-f32845ea-6d69-4462-8201-b28764d2bf3c.pklz 
190603-13:22:31,384 nipype.utils ERROR:
	 Your Nipype version is: 1.2.1-dev
190603-13:22:31,385 nipype.utils ERROR:
	 Nipype version of the pkl is: 1.1.2
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/nipypecli", line 11, in <module>
    load_entry_point('nipype', 'console_scripts', 'nipypecli')()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/src/nipype/nipype/scripts/cli.py", line 94, in crash
    display_crash_file(crashfile, rerun, debug, dir)
  File "/src/nipype/nipype/scripts/crash_files.py", line 51, in display_crash_file
    crash_data = loadcrash(crashfile)
  File "/src/nipype/nipype/utils/filemanip.py", line 632, in loadcrash
    return loadpkl(infile, versioning=True)
  File "/src/nipype/nipype/utils/filemanip.py", line 683, in loadpkl
    raise e
  File "/src/nipype/nipype/utils/filemanip.py", line 659, in loadpkl
    unpkl = pickle.load(pkl_file)
ModuleNotFoundError: No module named 'CPAC'`

**Comment by anibalsolon** [comment]
Hi @malywladek 

Since you are using Docker, all the dependencies of C-PAC (itself included) would be only installed on Docker, and not in your host machine.

You can try to open the crash file from within Docker, using:
```
docker run -i --rm \
    -v `pwd`:/crash \
    --entrypoint 'nipypecli' \
    fcpindi/c-pac \
    crash /crash/crash-20190603-105913-root-check_func_scan.b0-f32845ea-6d69-4462-8201-b28764d2bf3c.pklz
```

I would also recommend adding the original volume bindings (the flags '-v' from your C-PAC docker run), so the crash file will have the required input files.

**Comment by malywladek** [comment]
Ok. Now I've got:
`Exception:

[!] The data configuration file you provided is missing a level under the
'func:' key. CPAC versions 1.2 and later use data configurations with an
additional level of nesting.


Example

func:

  rest01:

    scan: /path/to/rest01_func.nii.gz

    scan parameters: /path/to/scan_params.json


See the User Guide for more information.`


Does it mean that I have to provide data description as well? As I said
before I have just single session EPI series.

B.

pon., 3 cze 2019 o 15:43 Anibal Sólon <notifications@github.com> napisał(a):

**Comment by anibalsolon** [comment]
You just need to provide a new level in the YAML file, for each subject:
```
- anat: <......nii.gz>
  func:
    rest_run-1:
      scan: <......nii.gz>
```

just replace the `<......nii.gz>` with the actual file names.

**Comment by malywladek** [comment]
Thank You for the reply. I have modified data configuration file and added scan parameters as well. Now I get the following error:
`File: /outputs/crash/crash-20190605-092430-root-selectrest.b1-28c7ac01-940e-468e-a46c-c846be0880b9.pklz
Node: resting_preproc_sub-01_ses-1.func_gather_0.selectrest
Working directory: /tmp/resting_preproc_sub-01_ses-1/func_gather_0/_scan_rest/selectrest


Node inputs:

function_str = CPAC.utils.datasource.get_rest
resource = scan
rest_dict = {'scan_parameters': {'tr': 2.0, 'acquisition': 'alt+z2'}, 'rest': '/bids_dataset/sub-01/func/sub-01_task-rest_bold.nii.gz'}
scan = rest



Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function.py", line 158, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/utils/datasource.py", line 22, in get_rest
    file_path = rest_dict[scan][resource]
TypeError: string indices must be integers, not str`

**Comment by malywladek** [comment]
I've just found a solution. My data configuration file was bad formatted. Please provide clear manual for that purpose. It seems that the idea is well presented on the website but there is little information about indents and specific and user-defined fields. I attach my fixed data_config file.
