### ISSUE TITLE
GUI Pipeline Builder Errors 1.4.3

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#1009]
When trying to set a powers threshold of .25 for framewise displacement censoring, i get this error:
```Traceback (most recent call last):
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/pages/nuisance.py", line 954, in save_regressor
    sel = editor.compile_selector()
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/pages/nuisance.py", line 863, in compile_selector
    'value': self.parse_threshold(self.data_controls['Censor']['threshold']['fdp']['value']),
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/pages/nuisance.py", line 779, in parse_threshold
    threshold = float(threshold)
TypeError: float() argument must be a string or a number
```

My choices for censoring are not saved.

Also, but without an error being displayed, the GUI doesn't save changes to the acompcor selection of WM and CS.

**Comment by anibalsolon** [comment]
I woud guess that you need to provide '0.25', but we can treat this case. I will update the code and let you know.
