### ISSUE TITLE
Docker (most recent as of 6/20) Crashes on read of pipeline config

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#1010]
```Traceback (most recent call last):
  File "/code/run.py", line 513, in <module>
    tracking=not args.tracking_opt_out)
  File "/code/CPAC/pipeline/cpac_runner.py", line 322, in run
    p_name, plugin, plugin_args)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1969, in prep_workflow
    name='nuisance_{0}_{1}'.format(regressors_selector_i, num_strat)
  File "/code/CPAC/nuisance/nuisance.py", line 866, in create_nuisance_workflow
    .format(anatomical_at_resolution_key)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 155, in __init__
    super(Node, self).__init__(name, kwargs.get('base_dir'))
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/base.py", line 39, in __init__
    self.name = name
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/base.py", line 52, in name
    raise ValueError('[Workflow|Node] name "%s" is not valid.' % name)
ValueError: [Workflow|Node] name "Anatomical_2.0mm_flirt" is not valid.
```

Here is my pipeline config:
[STDpipe.yml.txt](https://github.com/FCP-INDI/C-PAC/files/3317573/STDpipe.yml.txt)

**Comment by nimzodisaster** [comment]
mprage is already skull stripped, if relevant.

**Comment by anibalsolon** [comment]
Thank you for the bug report @nimzodisaster !

Could you please update your pipeline, by setting the extraction resolutions to '2', instead of '2.0' ? We will make it possible to use decimals in this config. BTW was this config generated by the GUI?

**Comment by nimzodisaster** [comment]
Removing the decimal removed the issue.
I thought I created this with GUI, but not with docker (I also have it installed most recent github version). However, I did have to manually edit some things (I reported that bug in another recent thread), and cannot guarantee I didn't change it to 2.0.
