### ISSUE TITLE
Better error message for missing site directory in S3 link

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1029]
When an S3 link is given to the Docker container and there is no site folder specified:

> Connecting to AWS: fcp-indi anonymously...
> gathering files from S3 bucket (s3.Bucket(name='fcp-indi')) for data/Projects/ADHD200/RawDataBIDS
> Traceback (most recent call last):
>   File "/code/run.py", line 434, in <module>
>     args.aws_input_creds)
>   File "/code/bids_utils.py", line 347, in bids_gen_cpac_sublist
>     bids_config_dict = bids_parse_sidecar(config_dict)
>   File "/code/bids_utils.py", line 208, in bids_parse_sidecar
>     bids_config.update(t_config)
> ValueError: dictionary update sequence element #0 has length 24; 2 is required

**Comment by sgiavasis** [comment]
This is in v1.6.1.
