### ISSUE TITLE
detect_qpp error

### ISSUE THREAD

**Issue by longfangithub** [FCP-INDI/C-PAC#1031]
Hi CPAC Team,
When QPP analysis is running on docker or with CPAC installed, the following error occurred:
NameError: global name 'np' is not defined.
Details are as follows:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function.py", line 158, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/qpp/pipeline.py", line 42, in detect_qpp
    convergence_iterations
  File "/code/CPAC/qpp/qpp.py", line 47, in detect_qpp
    random_state = check_random_state(random_state)
  File "/code/CPAC/utils/utils.py", line 449, in check_random_state
    return np.random.mtrand._rand
NameError: global name 'np' is not defined

**Comment by anibalsolon** [comment]
Thank you for reporting @longfangithub ! It is indeed a bug.
We will address it in the next C-PAC version.
