### ISSUE TITLE
Trouble pulling from ADHD200 with C-PAC container

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1094]
When pulling from:

`s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS`

instead of directly from a site like this:

`s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU`

you get this very confusing error:

> Traceback (most recent call last):
>   File "/code/run.py", line 492, in <module>
>     args.aws_input_creds
>   File "/code/bids_utils.py", line 347, in bids_gen_cpac_sublist
>     bids_config_dict = bids_parse_sidecar(config_dict)
>   File "/code/bids_utils.py", line 208, in bids_parse_sidecar
>     bids_config.update(t_config)
> ValueError: dictionary update sequence element #0 has length 24; 2 is required

Need to either fix it so it can handle multi-site, or provide a better error message.

**Comment by sgiavasis** [comment]
This is in v1.6.1.
