### ISSUE TITLE
Need better error message for nuisance regression option formatting error

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1099]
This is too vague:

```
Traceback (most recent call last):
  File "/code/run.py", line 590, in <module>
    tracking=not args.tracking_opt_out
  File "/code/CPAC/pipeline/cpac_runner.py", line 342, in run
    p_name, plugin, plugin_args)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 2050, in prep_workflow
    name='nuisance_{0}_{1}'.format(regressors_selector_i, num_strat)
  File "/code/CPAC/nuisance/nuisance.py", line 1247, in create_nuisance_workflow
    if 'type' not in threshold or threshold['type'] not in ['DVARS', 'FD_J', 'FD_P']:
TypeError: string indices must be integers, not str
```

**Comment by shnizzedy** [comment]
@sgiavasis do you know if this is still an issue or if it was the same as [this one](https://github.com/FCP-INDI/C-PAC/pull/2011#string%20indices%20must%20be%20integers)?
