### ISSUE TITLE
    C-PAC CerebrospinalFluid_mean has no output called stats

### ISSUE THREAD

**Issue by katkaz18** [FCP-INDI/C-PAC#1102]
Hi,

I am new to C-PAC and was trying to run the default pipeline for my data, however I keep getting this error. Could anyone please tell me what could be fix for that, because I can't locate it anywhere in the script?   

 C-PAC version: 1.5.0

    Setting maximum number of cores per participant to 1
    Setting number of participants at once to 1
    Setting OMP_NUM_THREADS to 1
    Setting MKL_NUM_THREADS to 1
    Setting ANTS/ITK thread usage to 1
    Maximum potential number of cores that might be used during this run: 1

Traceback (most recent call last):
  File "/home/X/miniconda/envs/cpac/bin/cpac", line 5, in <module>
    main()
  File "/home/X/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/X/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/X/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/X/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/X/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/X/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/__main__.py", line 145, in run
    debug=debug)
  File "/home/X/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_runner.py", line 342, in run
    p_name, plugin, plugin_args)
  File "/home/X/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 2050, in prep_workflow
    name='nuisance_{0}_{1}'.format(regressors_selector_i, num_strat)
  File "/home/X/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/nuisance/nuisance.py", line 1177, in create_nuisance_workflow
    build_nuisance_regressors, regressor_arg
  File "/home/X/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 214, in connect
    '\n'.join(['Some connections were not found'] + infostr))
Exception: Some connections were not found
Module CerebrospinalFluid_mean has no output called stats

**Comment by sgiavasis** [comment]
Hello @katkaz18,
Thanks for also creating an issue, saved us the step :)

Thread continues here:
https://groups.google.com/forum/#!topic/cpax_forum/d7O7sYv03G8

**Comment by SucyLi** [comment]
Hi @katkaz18, I was asking if you could send us your sample data, data config and pipeline config to us to replicate your error and we haven't heard from you yet. I will close this issue for now and let us know if you have any follow-up questions.
