### ISSUE TITLE
Singularity container no FSL error

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1184]
C-PAC v1.6.0 Singularity container pulled from Singularity Hub (works for many others).
This user has Singularity client version `singularity version 3.2.0-586.g6c159d1`.

User is getting this error:

```
Traceback (most recent call last):
  File "/code/run.py", line 588, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 344, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 283, in prep_workflow
    check_centrality_lfcd=check_centrality_lfcd)
  File "/code/CPAC/utils/utils.py", line 1156, in check_system_deps
    raise Exception(err)
Exception:

[!] CPAC says: It appears the following software packages are not installed or configured properly:

FSL

Consult the CPAC Installation Guide for instructions.
```

**Comment by sgiavasis** [comment]
This was resolved with a simple re-pull. Not sure of source of problem.
