### ISSUE TITLE
crash issue: prevent one of the histogram graphs from being created in QC

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1193]
```Node: resting_preproc_sub-0025427_ses-1.hist_vmhc_raw_score_0
Working directory: /outputs/working/resting_preproc_sub-0025427_ses-1/_scan_rest_run-1/_selector_CSF-2mm-M_aC-CSF+WM-2mm-PC5_M-SDB_P-1_BP-B0.01-T0.1/_fwhm_4/_target_angle_deg_90/hist_vmhc_raw_score_0
Node inputs:
function_str = CPAC.qc.utils.gen_histogram
measure = vmhc_raw_score
measure_file = /outputs/working/resting_preproc_sub-0025427_ses-1/_scan_rest_run-1/_selector_CSF-2mm-M_aC-CSF+WM-2mm-PC5_M-SDB_P-1_BP-B0.01-T0.1/_fwhm_4/_target_angle_deg_90/pearson_correlation_0/median_angle_corrected_maths_warp_tcorr.nii.gz
Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function.py", line 158, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/qc/utils.py", line 1355, in gen_histogram
    hist_path = make_histogram(measure_file, measure)
  File "/code/CPAC/qc/utils.py", line 1395, in make_histogram
    y, binEdges = np.histogram(data_flat[data_flat != 0], bins=100)
  File "/usr/local/miniconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.```


range parameter inf/nan in input data.
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/qc/utils.py#L1395

**Comment by sgiavasis** [comment]
Resolved in v1.6.2.
