### ISSUE TITLE
User having difficulty running MDMR

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1214]
They are running with:
```
docker run --user `id -u`:`id -g` --security-opt=apparmor:unconfined -i --rm -v /data3/autism_center/projects/patricia/ffa-acc/out1:/out1 -v /data3/autism_center/projects/patricia/ffa-acc/group_analysis:/group_analysis -v /data3/autism_center/projects/patricia/ffa-acc/group_analysis:/scratch -v /data3/autism_center/projects/patricia/ffa-acc/group_analysis:/log -v /data3/autism_center/wave2/BIDS:/bids_dataset -v /data3/autism_center/resources/cpac_resources/parc/:/Schaefer2018_400Parcels_17Networks_order_FSLMNI152_2mm.nii.gz fcpindi/c-pac:release-v1.6.0 /bids_dataset /out1 group --group_file /group_analysis/group_config.yml --save_working_dir --tracking_opt-out --n_cpus 4 --mem_gb 4
```

And are getting:
```
/code/CPAC/pipeline/cpac_group_runner.py:134: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 keys[keys['Derivative'] == 'yes'][keys['Space'] == 'template'][
/code/CPAC/pipeline/cpac_group_runner.py:135: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 keys['Values'] == 'z-score']['Resource'])
/code/CPAC/pipeline/cpac_group_runner.py:137: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 keys[keys['Derivative'] == 'yes'][keys['Space'] == 'template'][
/code/CPAC/pipeline/cpac_group_runner.py:138: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 keys['Values'] == 'z-stat']['Resource'])
/code/CPAC/pipeline/cpac_group_runner.py:140: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 keys[keys['Derivative'] == 'yes'][keys['Space'] == 'template'][
/code/CPAC/pipeline/cpac_group_runner.py:141: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 keys['Values'] == 'r-to-z']['Resource'])
Traceback (most recent call last):
 File "/code/run.py", line 304, in <module>
Starting group level analysis of data in /bids_dataset using /group_analysis/group_config.yml
Gathering the output file paths from /out1...
  cgr.run(args.group_file)
 File "/code/CPAC/pipeline/cpac_group_runner.py", line 2067, in run
  run_cwas(config_file)
 File "/code/CPAC/pipeline/cpac_group_runner.py", line 1346, in run_cwas
  inclusion=inclusion)
 File "/code/CPAC/pipeline/cpac_group_runner.py", line 1276, in run_cwas_group
  get_func=True)
 File "/code/CPAC/pipeline/cpac_group_runner.py", line 497, in gather_outputs
  exts
 File "/code/CPAC/pipeline/cpac_group_runner.py", line 201, in gather_nifti_globs
  raise Exception(err)
Exception: 
[!] No output filepaths found in the pipeline output directory provided for the derivatives selected!
Pipeline output directory provided: /out1
Derivatives selected:['functional_to_standard']
```

**Comment by sgiavasis** [comment]
This specific issue has been resolved (for those who are seeing this exact error message). This fix is available in 1.6.1a (latest).

However, a related issue persists where session and scan slicing is not working completely. This is being addressed in 1.6.2.
