### ISSUE TITLE
Data config KeyError: 'scantype' when hidden files in data directory

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1253]
User gets this error when there are .* hidden files in the BIDS data directory:

```
Traceback (most recent call last):
  File "/code/run.py", line 494, in <module>
    args.aws_input_creds
  File "/code/bids_utils.py", line 361, in bids_gen_cpac_sublist
    bids_config_dict = bids_parse_sidecar(config_dict)
  File "/code/bids_utils.py", line 191, in bids_parse_sidecar
    f_dict = bids_decode_fname(cp)
  File "/code/bids_utils.py", line 61, in bids_decode_fname
    if not f_dict["scantype"]:
KeyError: 'scantype'
```

**Comment by SucyLi** [comment]
related issue: https://github.com/FCP-INDI/C-PAC/issues/1223

**Comment by sgiavasis** [comment]
My fault, didn't realize there was already an issue.

**Comment by sgiavasis** [comment]
This will be resolved in next release; it was a little bit of rigidity in the BIDS parser.
