### ISSUE TITLE
♻️ `maxdisp`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1298]
**Describe the bug**

`maxdisp` is marked `# to be updated`

https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/CPAC/generate_motion_statistics/generate_motion_statistics.py#L429-L431

and is used but is not defined if `motion_correct_tool` is not in `{'3dvolreg', 'mcflirt'}`

https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/CPAC/generate_motion_statistics/generate_motion_statistics.py#L409-L414

which results in 

```Python
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)

  File "/code/CPAC/utils/interfaces/function.py", line 152, in _run_interface
    out = function_handle(**args)

  File "/code/CPAC/generate_motion_statistics/generate_motion_statistics.py", line 429, in gen_motion_parameters
    ('Mean_Relative_Maxdisp', avg_relative(maxdisp)), # to be updated

UnboundLocalError: local variable 'maxdisp' referenced before assignment
```

Since those are the only options for `motion_correct_tool`,
https://github.com/FCP-INDI/C-PAC/blob/33e22b281e907f1008da0371a15513047cfabd11/dev/docker_data/default_pipeline.yml#L604-L605

 this shouldn't necessarily be an issue. However, these `UnboundLocalErrors` are revealing that `motion_correct_tool` is not always making it to where it should be, as evidenced by log lines like

```Python
200606-00:00:33,108 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calc_motion_parameters.b0
```
 ― the third `None` there is `motion_correct_tool`:
https://github.com/FCP-INDI/C-PAC/blob/33e22b281e907f1008da0371a15513047cfabd11/CPAC/pipeline/cpac_pipeline.py#L2213-L2218

**To Reproduce**
The error logs in here were generated by running with [this pipeline configuration](https://github.com/FCP-INDI/C-PAC/files/4753307/rest_test_CPACv1.6.2_nuis1-3a.txt)

**Versions** 
 - C-PAC: https://github.com/FCP-INDI/C-PAC/commit/a9ae37ec31141d8700136c9cb1a5e40b178c52f4 ([Ⓢ](https://2244-4733263-gh.circle-artifacts.com/0/cpac-singularity-image.simg) [:whale:](https://2244-4733263-gh.circle-artifacts.com/0/cpac-docker-image.tar.gz))
 - Container Platform :
    - Singularity: 2.5.2

**Additional context**
https://github.com/FCP-INDI/C-PAC/pull/1291#issuecomment-638497379

**Comment by sgiavasis** [comment]
I would like to fold this in to a bigger (but not that big) effort to condense the motion metrics that C-PAC writes out. Perhaps into cleaner, and fewer, TSVs.

Marking this for v1.8.1, at least for now.
