### ISSUE TITLE
Calc Ants Warp Crashing

### ISSUE THREAD

**Issue by cbin-cnl** [FCP-INDI/C-PAC#1308]
Current Behavior: 

CPAC seems to be crashing on the calc_ants_warp stage

Environment:
Ubuntu 16.04 using Docker Image fcpindi/c-pac
CPAC version 1.6.2

Description:
I'm trying to use CPAC to preprocess some HCP data, and it seems like it's crashing on calc_ants_warp.

The crashfile yields this error:
```
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 449, in run
    emptydirs(outdir, noexist_ok=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 828, in emptydirs
    raise ex
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 818, in emptydirs
    shutil.rmtree(path)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/configs/working/resting_preproc_114823_114823/anat_mni_ants_register_0/calc_ants_warp'
```
However, there are crashes after that, which appear to be crashes in the cleanup code

```
Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 569, in run
    vals = np.loadtxt(mon_sp.fname, delimiter=',')
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: .proc-1_time-1593184345.0008287_freq-1.00 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 475, in run
    os.remove(hashfile_unfinished)
FileNotFoundError: [Errno 2] No such file or directory: '/configs/working/resting_preproc_114823_114823/anat_mni_ants_register_0/calc_ants_warp/_0xca3415ec04dec5e5dc236e6ffb4420bf_unfinished.json'

```

The crash doesn't seem to be happening for all subjects. Any information would be helpful.

**Comment by sgiavasis** [comment]
Hello,

This looks like it might have something to do with how Nipype is managing the working directory.
Roughly what percentage of subjects is this happening for?

I'd like to see if this happens for the failed subjects every time.
As a test, if you take one of the subjects that failed- what happens if you completely delete this directory:
`/configs/working/resting_preproc_114823_114823/anat_mni_ants_register_0/calc_ants_warp`

Then restart the pipeline for that subject?

Steve
