### ISSUE TITLE
crash: ndmg_create_graphs

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1332]
**crash describe**

- crash file

root@b5721eb5dfe4:/outputs/crash# nipypecli crash crash-20200722-155403-UID1101-ndmg_graphs_0.a1.b0-b0e5bec5-e117-4a77-aaa8-9ba626fa9af2.pklz

File: /outputs/crash/crash-20200722-155403-UID1101-ndmg_graphs_0.a1.b0-b0e5bec5-e117-4a77-aaa8-9ba626fa9af2.pklz
Node: resting_preproc_sub-ag150519a_ses-1.ndmg_graphs_0
Working directory: /outputs/working/resting_preproc_sub-ag150519a_ses-1/_scan_rest/_mask_S1_dx_mask_file_..template..03a_seeds..S1_dx.nii.gz/ndmg_graphs_0

Node inputs:

function_str = CPAC.utils.ndmg_utils.ndmg_create_graphs
labels = ['/template/03a_seeds/S1_dx.nii.gz']
ts = <undefined>

Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1250, in _run_interface
    self.config['execution']['stop_on_first_crash'])))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1172, in _collate_results
    (self.name, '\n'.join(msg)))
Exception: Subnodes of node: ndmg_graphs_0 failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 106, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)

  File "/code/CPAC/utils/interfaces/function.py", line 152, in _run_interface
    out = function_handle(**args)

  File "/code/CPAC/utils/ndmg_utils.py", line 236, in ndmg_create_graphs
    conn = connectome.cor_graph(ts)

  File "/code/CPAC/utils/ndmg_utils.py", line 170, in cor_graph
    rois = timeseries[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

- path

/data3/cnl/rodent/cpac_run/output/rodent_0722_2020_cpac17master-test_mcflirt_on_nuisance_woGS_onesub/crash

- command

/data3/cnl/rodent/cpac_run/run_bash/rodent_run_tse_onnuisance_0721.sh

**Comment by sgiavasis** [comment]
This is what I have so far.

ndmg_graph is tripping up because it's not getting anything for the time series- from the working directory:
```
Node: ndmg_graphs_1 (interfaces)
================================


 Hierarchy : resting_preproc_sub-ag150519a_ses-1.ndmg_graphs_1
 Exec ID : ndmg_graphs_1.a0.a1.b0


Original Inputs
---------------


* function_str : CPAC.utils.ndmg_utils.ndmg_create_graphs
* labels : ['/template/03a_seeds/S1_dx.nii.gz']
* ts : <undefined>
```

Looking at the code, we can see ndmg_graphs takes in an array object containing the extracted time series from ROI extraction, instead of the written-out CSV/TSV file:
https://github.com/FCP-INDI/C-PAC/blob/3013a060516c9a39be023c80afe0adfc9fc8407d/CPAC/timeseries/timeseries_analysis.py#L147-L151
https://github.com/FCP-INDI/C-PAC/blob/3013a060516c9a39be023c80afe0adfc9fc8407d/CPAC/timeseries/timeseries_analysis.py#L269
https://github.com/FCP-INDI/C-PAC/blob/3013a060516c9a39be023c80afe0adfc9fc8407d/CPAC/pipeline/cpac_pipeline.py#L2770-L2778

However, the output of clean_roi_csv is successfully producing the array object output:
```
Node: roi_timeseries_0 (clean_roi_csv (utility)
===============================================


 Hierarchy : resting_preproc_sub-ag150519a_ses-1.roi_timeseries_0.clean_roi_csv
 Exec ID : clean_roi_csv.a1.b0

...

* roi_array : [[15287.84082  15244.629395 15106.805664 ... etc.
```

I'm not yet sure why, will report back.

**Comment by sgiavasis** [comment]
I have not seen this issue for a long time and I believe it has been resolved with recent changes.
