### ISSUE TITLE
crash: filtering only in nuisance

### ISSUE THREAD

**Issue by SucyLi** [FCP-INDI/C-PAC#1335]
## C-PAC Run Info 

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Description**     | filtering only in nuisance strategy                              |
| **Version**            | v1.6.2a - v1.7.0                                        |    
| **Container**            | Docker                                        |
| **System**            | Linux                                          |    
| **Data Size**  | 295                         |
| **Results**     | crash at nuisance part                              |

**Include:**
- Output Path
```
/data3/cnl/fmriprep/preprocessed_AllNew_New/Full/CPAC_1.6.2/CPAC_fMRIPrep_MNI2006_2mm_filter_1_nuisance_0
```

- Pipeline Config
```
runNuisance: [1]

Regressors:
- Bandpass:
    bottom_frequency: 0.01
    top_frequency: 0.08
```
- Crash
```
Node inputs:

TR = <undefined>
args = <undefined>
automask = <undefined>
bandpass = <undefined>
blur = <undefined>
cenmode = <undefined>
censor = <undefined>
censortr = <undefined>
concat = <undefined>
dsort = <undefined>
environ = {}
in_file = /outputs/working/resting_preproc_sub-0025434a_ses-1/func_preproc_fsl_afni_mean_mcflirt_0/_scan_rest_run-1/func_normalize/sub-0025434a_task-rest_run-1_bold_calc_tshift_resample_mcf_calc_maths.nii.gz
mask = /outputs/working/resting_preproc_sub-0025434a_ses-1/func_preproc_fsl_afni_mean_mcflirt_0/func_preproc_fsl_afni_mean_mcflirt_0_skullstrip/_scan_rest_run-1/combine_masks/sub-0025434a_task-rest_run-1_bold_calc_tshift_resample_mcf_tstat_brain_mask_maths.nii.gz
noblock = <undefined>
norm = False
num_threads = 1
ort = <undefined>
out_file = residuals.nii.gz
outputtype = NIFTI_GZ
polort = 0
stopband = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 408, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 294, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 488, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 531, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 276, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 103, in validate
    validated_value = super(File, self).validate(object, name, value)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'ort' trait of a TProjectInputSpec instance must be an existing file name, but a value of None <class 'NoneType'> was specified.
Error setting node input:
Node: nuisance_regression
input: ort
results_file: /outputs/working/resting_preproc_sub-0025434a_ses-1/nuisance_regressor_0_0/_scan_rest_run-1/_selector_BP-B0.01-T0.08/build_nuisance_regressors/result_build_nuisance_regressors.pklz
value: None
```

**Comment by sgiavasis** [comment]
Resolved in v1.7.1.
