### ISSUE TITLE
🐛 [User-reported Bug]

### ISSUE THREAD

**Issue by opennog** [FCP-INDI/C-PAC#1467]
**Describe the bug**
It is the first time I'm running this tool, and I get the follwing error. I believe I installed everything as expected. But please, can anyone check what's going on?
Connecting nuisance_regression...
...
KeyError: "When trying to connect node block 'nuisance_regression' to workflow 'cpac_sub-010_ses-1' after node block 'erode_mask_WM': from-template_to-T1w_mode-image_desc-linear_xfm"

**To Reproduce**
cpac run --data_config_file ./data_config_prueba.yml bids/data2/ outputs/ participant --pipeline_file pipeline_config.yml

**Expected behavior**
It shuld run the command on the data available

**Screenshots**
![Screenshot from 2021-03-18 12-33-06](https://user-images.githubusercontent.com/29249551/111619682-281ab980-87e6-11eb-9907-7b09c188eb8a.png)

**Versions** 
 - C-PAC: 1.8.0
 - Container Platform Docker
 -

**Comment by shnizzedy** [comment]
Hi @opennog,

Thanks for reporting this issue. Are you comfortable sharing your `pipeline_config.yml`? Seeing the configuration should help us uncover what's preventing your pipeline from compiling.

**Comment by opennog** [comment]
Sure, here it is
Thanks for the prompt reply.

[pipeline_config.zip](https://github.com/FCP-INDI/C-PAC/files/6164941/pipeline_config.zip)

On the other hand, running the default pipeline on the same data, after 1h or analysis it gives me another error related to the same nuisance regression... I don't know if they are related. But I do really appreciate your help.
Error: 
FileNotFoundError: /tmp/cpac_sub-010_ses-1/nuisance_regression_defaultNoGSR_144/_scan_rest/nuisance_regression/result_nuisance_regression.pklz

Thanks!

**Comment by shnizzedy** [comment]
```Python
KeyError: "When trying to connect node block 'nuisance_regression' to workflow 'cpac_sub-10_ses-1' after node block 'erode_mask_WM': from-template_to-T1w_mode-image_desc-linear_xfm"
```

indicates that your configuration is expecting to expect `from-template_to-T1w_mode-image_desc-linear_xfm` to not exist but to be necessary to run this pipeline configuration. In this particular case, C-PAC may be mistaken. 

C-PAC is looking for the necessary inputs for the regressors listed in `nuisance_corrections['2-nuisance_regression']['Regressors']` even though `nuisance_corrections['2-nuisance_regression']['run']` is set to `[Off]`. As a workaround, you can set `Regressors` empty (
   ```YAML
   nuisance_corrections:
     2-nuisance_regression:
       Regressors:
   ```

   instead of 

   ```YAML
   nuisance_corrections:
     2-nuisance_regression:
       Regressors:
         -  Name: 'default'
            …
         -  Name: 'defaultNoGSR'
            …
   ```

   )

With that change, I get

```Python
Run called with config file /media/ebs/runs/2021-03-18/opennog/cpac_pipeline_config_2021-03-18T21-36-34Z.yml
210318-21:36:36,332 nipype.workflow INFO:
	 

    C-PAC version: 1.8.0

    Setting maximum number of cores per participant to 1
    Setting number of participants at once to 1
    Setting OMP_NUM_THREADS to 1
    Setting MKL_NUM_THREADS to 1
    Setting ANTS/ITK thread usage to 1
    Maximum potential number of cores that might be used during this run: 1



Output directory /media/ebs/runs/2021-03-18/opennog/output does not exist yet, initializing.
Connecting anatomical_init...

Connecting brain_mask_afni...

Connecting brain_extraction...

Connecting coregistration_prep_mean...

Connecting timeseries_extraction_AVG...

Connecting spatial_regression...

Connecting SCA_AVG...

Connecting dual_regression...

Connecting multiple_regression...

Connecting alff_falff...

Traceback (most recent call last):
  File "/code/run.py", line 677, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 549, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 359, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1134, in build_workflow
    wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 860, in connect_pipeline
    wf = nb.connect_block(wf, cfg, rpool)
  File "/code/CPAC/pipeline/engine.py", line 1203, in connect_block
    pipe_x, opt)
  File "/code/CPAC/alff/alff.py", line 270, in alff_falff
    node, out = strat_pool.get_data('space-bold_desc-brain_mask')
  File "/code/CPAC/pipeline/engine.py", line 281, in get_data
    return self.get(resource)['data']
  File "/code/CPAC/pipeline/engine.py", line 252, in get
    raise LookupError("\n\n[!] C-PAC says: The listed resource is "
LookupError: When trying to connect node block 'alff_falff' to workflow 'cpac_3699991_1' after node block 'multiple_regression': 

[!] C-PAC says: The listed resource is not in the resource pool:
space-bold_desc-brain_mask

Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.
```

but your input directory might contain `space-bold_desc-brain_mask`; mine does not. If not, turning `amplitude_low_frequency_fluctuation['run']` and `regional_homogeneity['run']` off or turning `functional_preproc['run']` on should get the rest of your pipeline configuration to run.

---

The main pipeline connector in C-PAC 1.8.0 is something we're still refining. Because C-PAC is intended to work at various points with either existing data or self-generated data, a given pipeline configuration could work with one data directory and not with another, depending on what processed data is provided.

Of course you want to run what you want to run and avoid unnecessary steps. What is your goal with this pipeline configuration?

**Comment by sgiavasis** [comment]
Citing this in #1345 for version 1.8.1: https://github.com/FCP-INDI/C-PAC/milestone/20
