### ISSUE TITLE
✨NHP pipeline benchmark

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1481]
Monkey TODO list:
- [ ] 1. T2 ingress  + T2 preproc + T2toT1Reg + biasfield correction -T1wT2w

- merged branch: https://github.com/FCP-INDI/C-PAC/tree/feature/T2

https://github.com/FCP-INDI/C-PAC/tree/feature/T2ingress
https://github.com/FCP-INDI/C-PAC/tree/feature/T2preproc
https://github.com/FCP-INDI/C-PAC/tree/feature/T2toT1Reg
optional coreg flirt code https://github.com/HechengJin0/dcan-macaque-pipeline/blob/master/fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh#L531
optional fov tool for acpc

- [ ] Test:

- [ ] 2. preliminary mask (3 cases: ANTs based (no edited mask), have T1_edit_mask, have T1_initial_mask)
https://github.com/HechengJin0/dcan-macaque-pipeline/blob/master/PreliminaryMasking/macaque_masking.py#L144-L158

- [ ] 3. using T2w image to generate functional mask (this mask is temporal mask used in coreg) 

https://github.com/HechengJin0/dcan-macaque-pipeline/blob/master/fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh#L359-L363 

- [ ] 4. functional masking in standard space.  CPAC does functional skullstripping then transfer to standard space.

**Comment by HechengJin0** [comment]
1. feature/T2 branch test
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 379, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1003, in build_workflow
    wf, rpool = initiate_rpool(wf, cfg, sub_dict)
  File "/code/CPAC/pipeline/engine.py", line 1819, in initiate_rpool
    part_id, ses_id)
  File "/code/CPAC/pipeline/engine.py", line 1338, in ingress_raw_anat_data
    anat=data_paths['anat']['T1w'],
TypeError: string indices must be integers
```

**Comment by HechengJin0** [comment]
[test_build_workflow ](https://github.com/FCP-INDI/C-PAC/blob/feature/T2/CPAC/pipeline/test/test_engine.py#L121-L157)function is hanging. 
on my local 
hanging after
```Connecting anatomical_init...

Connecting brain_mask_acpc_afni...

Connecting brain_extraction...

Connecting acpc_alignment_brain...

Connecting brain_mask_afni...

Connecting brain_extraction...

Connecting anatomical_init_T2...

Connecting brain_mask_acpc_afni_T2...

Connecting brain_extraction_T2...

Connecting acpc_alignment_brain_T2...

Connecting registration_T2w_to_T1w...

Connecting t1t2_bias_correction...

Connecting brain_mask_afni_T2...

Connecting brain_extraction_T2...

Connecting register_FSL_anat_to_template...

Connecting tissue_seg_ants_prior...

Connecting func_truncate...

Connecting func_reorient...

Connecting get_motion_ref...

Connecting motion_correction...

Connecting bold_mask_anatomical_refined...

Connecting bold_masking...

Connecting calc_motion_stats...

Connecting func_mean...

Connecting func_normalize...

Connecting coregistration_prep_vol...

Connecting coregistration...

Connecting create_func_to_T1template_xfm...

Connecting nuisance_regression...
```

**Comment by HechengJin0** [comment]
pipeline cofig: off functional_preproc. off coregistration. off func_registration_to_template

/data3/cnl/monkey_benchmark/cpac_run/benchmark_dcan/new_runs/monkey_0405_ucdavis_cpac181_ucdavis_cpac181_nomask_nofunc

why? 

```
Run called with config file /outputs/cpac_pipeline_config_2021-04-05T17-40-06Z.yml
210405-17:40:10,39 nipype.workflow INFO:
	 

    C-PAC version: 1.8.0

    Setting maximum number of cores per participant to 5
    Setting number of participants at once to 3
    Setting OMP_NUM_THREADS to 1
    Setting MKL_NUM_THREADS to 1
    Setting ANTS/ITK thread usage to 1
    Maximum potential number of cores that might be used during this run: 15



Output directory /outputs/output does not exist yet, initializing.
Connecting anatomical_init...

Connecting brain_mask_acpc_afni...

Connecting brain_extraction...

Connecting acpc_alignment_brain...

Connecting brain_mask_afni...

Connecting brain_extraction...

Connecting anatomical_init_T2...

Connecting brain_mask_acpc_afni_T2...

Connecting brain_extraction_T2...

Connecting acpc_alignment_brain_T2...

Connecting registration_T2w_to_T1w...

Connecting t1t2_bias_correction...

Connecting brain_mask_afni_T2...

Connecting brain_extraction_T2...

Connecting register_FSL_anat_to_template...

Connecting tissue_seg_ants_prior...

Connecting coregistration_prep_vol...

Connecting nuisance_regression...

Process Process-1:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 379, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1232, in build_workflow
    wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 958, in connect_pipeline
    wf = nb.connect_block(wf, cfg, rpool)
  File "/code/CPAC/pipeline/engine.py", line 1203, in connect_block
    pipe_x, opt)
  File "/code/CPAC/nuisance/nuisance.py", line 2023, in nuisance_regression_complete
    node, out = strat_pool.get_data('space-bold_desc-brain_mask')
  File "/code/CPAC/pipeline/engine.py", line 281, in get_data
    return self.get(resource)['data']
  File "/code/CPAC/pipeline/engine.py", line 252, in get
    raise LookupError("\n\n[!] C-PAC says: The listed resource is "
LookupError: When trying to connect node block 'nuisance_regression' to workflow 'cpac_sub-032125_ses-001' after node block 'erode_mask_WM': 

[!] C-PAC says: The listed resource is not in the resource pool:
space-bold_desc-brain_mask

Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.
```

**Comment by HechengJin0** [comment]
Q:
[epi supposed to be 'desc-acpcbrain_T2w', not 'desc-brain_T2w'
but why only 'desc-brain_T2w'? ](https://github.com/FCP-INDI/C-PAC/blob/feature/acpc_T2/CPAC/anat_preproc/anat_preproc.py#L1173)

/data3/cnl/monkey_benchmark/cpac_run/benchmark_dcan/new_runs/monkey_0415_ucdavis_cpac181_mask_nofunc/working/cpac_sub-032125_ses-001/T2w_to_T1w_Reg_82/T2w2T1w_reg
![image](https://user-images.githubusercontent.com/47699110/115338865-b382c400-a171-11eb-8a9d-65719dfa3394.png)

**Comment by HechengJin0** [comment]
brain extraction is not calling proper 'desc-preproc_T1w'. Seems 'desc-preproc_T1w' is not updated after [t1t2_bias_correction](https://github.com/FCP-INDI/C-PAC/blob/feature/acpc_T2/CPAC/anat_preproc/anat_preproc.py#L1261-L1266).
Supposed order: ACPC alignment(brain) - T2w_to_T1_reg - T1T2_bias_correction - Brain extraction
But, BrainExtraction is calling the head right after ACPC alignment. 

see `/data3/cnl/monkey_benchmark/cpac_run/benchmark_dcan/new_runs/monkey_0420_ucdavis_cpac181_mask_nofunc/working/cpac_sub-032125_ses-001/brain_extraction_62`

![image](https://user-images.githubusercontent.com/47699110/116505055-e3277f80-a887-11eb-80bd-0844c6369897.png)

**Comment by HechengJin0** [comment]
probably rename "space-T*w_desc-acpcbrain_mask" and "desc-acpcbrain_T*w". "space-T*w_desc-acpcbrain_mask" is the mask in individual space, indicates it used in acpc. "desc-acpcbrain_T*w" is the brain in acpc template space. might confuse people.

**Comment by HechengJin0** [comment]
`pipeline_config_on_func.yml` pipeline config setting: on coregistration. on func_registration_to_template. off functional_preproc. off nuisance.

**Comment by HechengJin0** [comment]
- [ ] update fix

/data3/cnl/monkey_benchmark/cpac_run/benchmark_dcan/new_runs/monkey_0511_ucdavis_cpac181_mask_func_test
issue: unable to set first volume as motion reference. 

```
Connecting func_reorient...

Connecting motion_correction...

Traceback (most recent call last):
  File "/code/run.py", line 677, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 549, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 373, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1215, in build_workflow
    wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 941, in connect_pipeline
    wf = nb.connect_block(wf, cfg, rpool)
  File "/code/CPAC/pipeline/engine.py", line 1204, in connect_block
    pipe_x, opt)
  File "/code/CPAC/func_preproc/func_preproc.py", line 1041, in func_motion_correct
    opt)
  File "/code/CPAC/func_preproc/func_preproc.py", line 783, in motion_correct_connections
    node, out = strat_pool.get_data('motion-basefile')
  File "/code/CPAC/pipeline/engine.py", line 281, in get_data
    return self.get(resource)['data']
  File "/code/CPAC/pipeline/engine.py", line 252, in get
    raise LookupError("\n\n[!] C-PAC says: The listed resource is "
LookupError: When trying to connect node block 'motion_correction' to workflow 'cpac_sub-032125_ses-001' after node block 'get_motion_ref': 

[!] C-PAC says: The listed resource is not in the resource pool:
motion-basefile

Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.
```

**Comment by HechengJin0** [comment]
- [ ] not running??? fcpindi/c-pac:feature_T2_coreg_func_mask

```
hjin@lisa:/data3/cnl/monkey_benchmark/cpac_run/benchmark_dcan/new_runs/monkey_0519_ucdavis_cpac181_mask_func_t2_coreg_dcan_style_func_to_standard$ bash run_dcan_ucdavis_func.sh 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
INFO: //matlab/startup.m does not exist ... creating
mkdir: cannot create directory ‘//matlab’: Permission denied
touch: cannot touch '//matlab/startup.m': No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 231: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 232: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 233: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 234: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 235: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 236: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 237: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 238: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 239: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 240: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 241: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 242: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 243: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 244: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 245: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 246: //matlab/startup.m: No such file or directory
/usr/lib/freesurfer/FreeSurferEnv.sh: line 247: //matlab/startup.m: No such file or directory
grep: //matlab/startup.m: No such file or directory
grep: //matlab/startup.m: No such file or directory
grep: //matlab/startup.m: No such file or directory
#### Running C-PAC
Number of participants to run in parallel: 1
Output directory: /outputs/output
Working directory: /outputs/working
Log directory: /outputs/log
Remove working directory: False
Available memory: 40.0 (GB)
Available threads: 16
Number of threads for ANTs: 1
Starting participant level processing
Run called with config file /outputs/cpac_pipeline_config_2021-05-19T14-42-54Z.yml
210519-14:42:57,330 nipype.workflow INFO:
	 

    C-PAC version: 1.8.0

    Setting maximum number of cores per participant to 16
    Setting number of participants at once to 1
    Setting OMP_NUM_THREADS to 1
    Setting MKL_NUM_THREADS to 1
    Setting ANTS/ITK thread usage to 1
    Maximum potential number of cores that might be used during this run: 16

```
