### ISSUE TITLE
✨ [User-requested Feature] change functional_registration under functional_preproc? 

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1482]
**Related problem**
what if I only want to run anatomical part.

**Proposed feature**
change functional_registration under functional_preproc

**Alternatives**
currently, functional_registration (e.g. coreg) must run, even if I turn off functional-preproc

got ```Connecting coregistration...

Process Process-1:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 379, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1232, in build_workflow
    wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 958, in connect_pipeline
    wf = nb.connect_block(wf, cfg, rpool)
  File "/code/CPAC/pipeline/engine.py", line 1203, in connect_block
    pipe_x, opt)
  File "/code/CPAC/registration/registration.py", line 2073, in coregistration
    node, out = strat_pool.get_data(['desc-reginput_bold', 'desc-mean_bold'])
  File "/code/CPAC/pipeline/engine.py", line 281, in get_data
    return self.get(resource)['data']
  File "/code/CPAC/pipeline/engine.py", line 243, in get
    raise Exception("\n[!] C-PAC says: None of the listed "
Exception: 
[!] C-PAC says: None of the listed resources are in the resource pool:
['desc-reginput_bold', 'desc-mean_bold']```

**Comment by sgiavasis** [comment]
Should be able to disable coregistration:
https://github.com/FCP-INDI/C-PAC/blob/master/dev/docker_data/default_pipeline.yml#L602-L607

Coregistration is treated as separate from functional preprocessing in this system so that users can simply decide to coregister raw (un-preprocessed) BOLD data to T1 if they wish to.

Is this more an issue that turning it Off doesn't work properly?

**Comment by sgiavasis** [comment]
I've made some progress in this with https://github.com/FCP-INDI/C-PAC/pull/1491

**Comment by shnizzedy** [comment]
Maybe fixed in #1647 / related to #1575 ― need to test
