### ISSUE TITLE
🐛 itk::ERROR: LabelStatisticsImageFilter(0x25bfaa0): Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1556]
### Describe the bug

```
Node: cpac_sub-NDARZP630WYL_ses-HBNsiteRU.n4_correct_102
Working directory: /outputs/working/cpac_sub-NDARZP630WYL_ses-HBNsiteRU/_scan_movieTP/n4_correct_102

Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = 200.0
bspline_order = <undefined>
convergence_threshold = <undefined>
copy_header = True
dimension = 3
environ = {'NSLOTS': '1'}
histogram_sharpening = <undefined>
input_image = <undefined>
mask_image = <undefined>
n_iterations = <undefined>
num_threads = 1
output_image = <undefined>
rescale_intensities = False
save_bias = False
shrink_factor = <undefined>
weight_image = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 745, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
N4BiasFieldCorrection --bspline-fitting [ 200 ] -d 3 --input-image /outputs/working/cpac_sub-NDARZP630WYL_ses-HBNsiteRU/_scan_movieTP/func_get_fmriprep_ref_83/ref_bold.nii.gz --mask-image /outputs/working/cpac_sub-NDARZP630WYL_ses-HBNsiteRU/_scan_movieTP/pre_mask_dilate_102/tpl-MNI152NLin2009cAsym_res-01_label-brain_probseg_trans_maths_dil.nii.gz --output ref_bold_corrected.nii.gz
Standard output:

Standard error:
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /src/ants/build/staging/include/ITK-5.1/itkImageSink.hxx:242:
itk::ERROR: LabelStatisticsImageFilter(0x25bfaa0): Inputs do not occupy the same physical space! 
InputImage Direction: 9.9871930e-01 5.0594102e-02 1.0727740e-05
4.9522723e-02 -9.7761382e-01 2.0449628e-01
-1.0356793e-02 2.0423384e-01 9.7886734e-01
, InputImagePrimary Direction: 9.9871931e-01 5.0593920e-02 8.8653188e-06
4.9522926e-02 -9.7761381e-01 2.0449627e-01
-1.0354935e-02 2.0423392e-01 9.7886734e-01

        Tolerance: 1.0000000e-06

Aborted
Return code: 134
```

### To reproduce

With [this subject](https://github.com/PennLINC/HBN_BIDS/tree/master/sub-NDARZP630WYL/ses-HBNsiteRU), [running on CUBIC](https://pennlinc.github.io/docs/TheWay/RunningDataLadPipelines/) with the following command

```BASH
qsub -cwd -v DSLOCKFILE=/cbica/projects/RBC/CPAC-1.8.1-TESTING/bootstrapped/hbn_exemplars/c-pac-1.8.1-dev/analysis/.SGE_datalad_lock -N c-pac_sub-NDARZP630WYL -e /cbica/projects/RBC/CPAC-1.8.1-TESTING/bootstrapped/hbn_exemplars/c-pac-1.8.1-dev/analysis/logs -o /cbica/projects/RBC/CPAC-1.8.1-TESTING/bootstrapped/hbn_exemplars/c-pac-1.8.1-dev/analysis/logs   /cbica/projects/RBC/CPAC-1.8.1-TESTING/bootstrapped/hbn_exemplars/c-pac-1.8.1-dev/analysis/code/participant_job.sh   ria+file:///cbica/projects/RBC/CPAC-1.8.1-TESTING/bootstrapped/hbn_exemplars/c-pac-1.8.1-dev/input_ria#ae10dc55-ba95-48e1-97a0-963032cf3dd8 /cbica/projects/RBC/CPAC-1.8.1-TESTING/bootstrapped/hbn_exemplars/c-pac-1.8.1-dev/output_ria/ae1/0dc55-ba95-48e1-97a0-963032cf3dd8 sub-NDARZP630WYL
```

which resolves via [this bootstrap script](https://github.com/FCP-INDI/TheWay/blob/9ef4c02/scripts/cubic/bootstrap-c-pac.sh) at runtime to

```BASH
subid="sub-NDARZP630WYL"
mkdir -p ${subid}_outputs
singularity run --cleanenv \
    -B ${PWD} \
    -B ${PWD}/${subid}_outputs:/outputs \
    pennlinc-containers/.datalad/environments/cpac-1-8-1-dev/image \
    inputs/data \
    /outputs \
    participant \
    --preconfig fx-options \
    --skip_bids_validator \
    --n_cpus 4 \
    --mem_gb 32 \
    --participant_label "$subid"

7z a ${subid}_c-pac-1.8.1-dev.zip ${subid}_outputs
rm -rf ${subid}_outputs
```

### Expected behavior

Run either completes without error or gives a clearer error message as to why it cannot.

### Acceptance criteria

Run either
- [ ] completes without error

or
- [ ] gives a clearer error message as to why it cannot.

### C-PAC version

v1.8.1-dev @ https://github.com/FCP-INDI/C-PAC/commit/81925d7683e9f8e452119fc0ee3bab00979c2c76

### Container platform

Singularity

### Docker and/or Singularity version(s)

3.7.4-1.el7

### Additional context

On an SGE cluster

**Comment by shnizzedy** [comment]
[ANTs v2.3.5: Ecphorella](https://github.com/ANTsX/ANTs/releases/tag/v2.3.5)'s release notes mention

> Incorporate ITK update that uses NIFTI sform transforms where possible, reducing precision errors in header orientation. More details at [this ANTs Wiki page](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F).

**Comment by shnizzedy** [comment]
:point_up: but I'm still hitting this error with that version of ANTs:

```
Singularity> N4BiasFieldCorrection --bspline-fitting [ 200 ] -d 3 --input-image /outputs/working/cpac_sub-NDARZP630WYL_ses-HBNsiteRU/_scan_movieTP/func_get_fmriprep_ref_83/ref_bold.nii.gz --mask-image /outputs/working/cpac_sub-NDARZP630WYL_ses-HBNsiteRU/_scan_movieTP/binarize_mask_102/tpl-MNI152NLin2009cAsym_res-01_label-brain_probseg_trans_maths.nii.gz --output ref_bold_corrected.nii.gz
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /tmp/ants/build/staging/include/ITK-5.2/itkImageSink.hxx:242:
itk::ERROR: itk::ERROR: LabelStatisticsImageFilter(0x5618556c9600): Inputs do not occupy the same physical space! 
InputImage Direction: 9.9871930e-01 5.0593979e-02 9.4861998e-06
4.9522858e-02 -9.7761381e-01 2.0449627e-01
-1.0355554e-02 2.0423390e-01 9.7886734e-01
, InputImagePrimary Direction: 9.9871935e-01 5.0593006e-02 0.0000000e+00
4.9523843e-02 -9.7761380e-01 2.0449604e-01
-1.0346069e-02 2.0423418e-01 9.7886739e-01

        Tolerance: 1.0000000e-06

Aborted
Singularity> antsRegistration --version
ANTs Version: 2.3.5.dev1-g6f137
Compiled: Aug 31 2021 14:14:11
```

**Comment by shnizzedy** [comment]
I'm hitting this with a handful of (4) participants from the RBC exemplars

**Comment by shnizzedy** [comment]
https://github.com/FCP-INDI/C-PAC/blob/80424468c7f4e59c102f446b05d4154ec1cd4b2d/CPAC/anat_preproc/anat_preproc.py#L1520-L1522

`desc-preproc_T1w` is the resource key for the T1w for both input and output, so if this node fails and `config['anatomical_preproc', 'brain_extraction', 'using'] ∌ 'FreeSurfer-ABCD'`, downstream nodes will proceed as if n4 bias correction was never attempted
