### ISSUE TITLE
🐛 [User-reported Bug]

### ISSUE THREAD

**Issue by tergeorge** [FCP-INDI/C-PAC#1627]
### Describe the bug

When a CPAC run is performed using docker after a failed run using the same output directory, you get an error telling you about missing json files. 
`'JSONDecodeError' object has no attribute 'message'`
The full error is given below:
 ```
File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/run.py", line 654, in <module>
    args.skip_bids_validator)
  File "/code/run.py", line 132, in create_cpac_data_config
    aws_input_creds)
  File "/code/bids_utils.py", line 553, in collect_bids_files_configs
    e.message))
AttributeError: 'JSONDecodeError' object has no attribute 'message'. 

```
This error message is confusing and it would be nice to have a more clear message on what the problem with the run is so that the user can make changes and do the required correction.

### To reproduce

1. Perform a C-PAC run using docker. 
2. If the run fails to complete or is interrupted, rerun it gain with the same output director. 
3. You should get the error similar to the one shown here.

### Expected behavior

A more clear message of the error that has occurred during the run  like 'Expecting json files in the output directory but none was found'.
or  ' Expecting {file_name} in the output directory but no such file found'. 

### Acceptance criteria

1. Edit error message to make it more direct and clear to the user. 
2. Provide a message to the user about how to go about resolving the error like using a new output directory for the new run.

**Comment by shnizzedy** [comment]
I believe that error usually happens when something goes wrong downloading something from an internet connection

**Comment by tergeorge** [comment]
oh okay. I guess the error message is still not clear and it would be nice to edit it.
