### ISSUE TITLE
🐛 [User-reported Bug]

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1686]
### Describe the bug

With a BIDS directory or data configuration structured like
```YAML
- anat:
    T1w:
    T2w:
  creds_path:
  fmap:
    diffmag:
  func:
  site_id:
  subject_id:
  unique_id
```

i.e., with `fmap.diffmag` but no `fmap.diffphase`, https://github.com/FCP-INDI/C-PAC/blob/80424468c7f4e59c102f446b05d4154ec1cd4b2d/CPAC/utils/datasource.py#L434-L452 will raise an execption like
```Python
Traceback (most recent call last):
  File "/code/run.py", line 762, in <module>
    run_main()
  File "/code/run.py", line 743, in run_main
    test_config=(1 if args.analysis_level == "test_config" else 0)
  File "/code/CPAC/pipeline/cpac_runner.py", line 565, in run
    raise e
  File "/code/CPAC/pipeline/cpac_runner.py", line 562, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 424, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1090, in build_workflow
    wf, rpool = initiate_rpool(wf, cfg, sub_dict)
  File "/code/CPAC/pipeline/engine.py", line 1904, in initiate_rpool
    part_id, ses_id)
  File "/code/CPAC/pipeline/engine.py", line 1495, in ingress_raw_func_data
    data_paths['creds_path'], ses_id)
  File "/code/CPAC/utils/datasource.py", line 451, in ingress_func_metadata
    node, out_file = rpool.get('diffphase_dwell')[
  File "/code/CPAC/pipeline/engine.py", line 254, in get
    raise LookupError(lookup_message)
LookupError: 

[!] C-PAC says: The listed resource is not in the resource pool:
diffphase_dwell

Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.
(keys in resource pool are dict_keys(['T1w', 'T2w', 'subject', 'bold', 'scan', 'scan_params', 'diffmag', 'diffmag_scan_params', 'diffmag_TE', 'diffmag_dwell', 'diffmag_pedir']))
```

### To reproduce

Try to run a pipeline with `fmap.diffmag` but no `fmap.diffphase`

### Expected behavior

```Python
[!] C-PAC says: The listed resource is not in the resource pool:
diffphase_dwell
```

is only raised if `diffphase` is needed for the pipeline

### Acceptance criteria

- [ ] `[!] C-PAC says: The listed resource is not in the resource pool: diffphase_dwell` is only raised if `diffphase` is needed for the pipeline

### C-PAC version

v1.8.3 & v1.8.2

### Container platform

Docker

### Docker and/or Singularity version(s)

Docker version 18.06.1-ce, build e68fc7a

### Additional context

This issue was discovered with an anatomical-only run on a BIDS directory

**Comment by diegoaper** [comment]
Hello! I tried to run only T1w and BOLD images but the BIDS directory also has an fmap sub-directory. I got this same error, I believe its when running CPAC with no data config file it'll extract all the information including the fmap folder. If there was a flag to only pull information from the anat and func folders I think it would solve the issue when creating the data config file.

**Comment by diegoaper** [comment]
Work-around: Create the data config file and remove all the sections of fmap that are not desired. Then remove the sequence parameters of func to allow the preprocessing of only anat and func even when there are other images in the same directory.
