### ISSUE TITLE
🐛 `convert_motionxfm2itk_188`: `c3d_affine_tool […] died with <Signals.SIGABRT: 6>`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1702]
### Describe the bug

```Python
Node: cpac_sub-colornest035_ses-1.convert_motionxfm2itk_188
Working directory: /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/convert_motionxfm2itk_188

Node inputs:

function_str = def run_c3d(reference_file, source_file, transform_file):

    import os
    import subprocess

    itk_transform = os.path.join(os.getcwd(), 'affine.txt')

    cmd = ['c3d_affine_tool', '-ref', reference_file, '-src',
            source_file, transform_file, '-fsl2ras', '-oitk', itk_transform]
    retcode = subprocess.check_output(cmd)

    return itk_transform

reference_file = <undefined>
source_file = <undefined>
transform_file = ['/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/oned_matrix_concat_86/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc.aff12.1D']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 388, in run
    return super().run(updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1295, in _collate_results
    "Subnodes of node: %s failed:\n%s" % (self.name, "\n".join(msg))
Exception: Subnodes of node: convert_motionxfm2itk_188 failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)

  File "<string>", line 10, in run_c3d

  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['c3d_affine_tool', '-ref', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/func_get_fmriprep_ref_83/ref_bold.nii.gz', '-src', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/func_get_fmriprep_ref_83/ref_bold.nii.gz', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/oned_matrix_concat_86/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc.aff12.1D', '-fsl2ras', '-oitk', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/convert_motionxfm2itk_188/mapflow/_convert_motionxfm2itk_1880/affine.txt']' died with <Signals.SIGABRT: 6>.
```

Running the command in a container:
```C
terminate called after throwing an instance of 'char const*'
```

### To reproduce

Run with

```YML
functional_preproc:
  motion_estimates_and_correction:
    motion_correction:
      using: [3dvolreg]
registration_workflows: 
  functional_registration:
    func_registration_to_template:
      apply_transform:
        using: single_step_resampling
```

### Expected behavior

`c3d_affine_tool` succeeds

### Acceptance criteria

- [ ] `c3d_affine_tool` succeeds
   or
- [ ] 'single_step_resampling' is explicitly disallowed for 3dvolreg

### C-PAC version

v1.8.4-dev

### Container platform

Singularity

### Docker and/or Singularity version(s)

Singularity 3.8.5-2.el7

**Comment by shnizzedy** [comment]
3dvolreg transform_file looks like

```TSV
# 3dvolreg matrices (DICOM-to-DICOM, row-by-row):
     0.999999   0.000192171   -0.00109756    -0.0165939  -0.000191084      0.999999   0.000990944      0.032994    0.00109775  -0.000990734      0.999999     0.0265386
     0.999999   0.000202603   -0.00153324    -0.0432548  -0.000200501      0.999999    0.00137106     0.0355761    0.00153351   -0.00137075      0.999998     0.0273235
[…]
```

(150 rows × 12 columns)

**Comment by shnizzedy** [comment]
### mcflirt

`*.mat` directory with 150 `MAT_*` files, each 4 × 4

### 3dvolreg

`*.1D` file with shape 152 × 12

**Comment by gkiar** [comment]
What about the right column? Are they 0s?

**Comment by gkiar** [comment]
Perfect. As discussed over Slack, the solution then is to reshape each 1 x 12 row into 3 x 4 and pad it with `0 0 0 1` to conform to the homogeneous coordinates standard.

**Comment by shnizzedy** [comment]
That did the trick!

https://github.com/FCP-INDI/C-PAC/blob/10f1d4d728bb0d9f5d530de8ab8a5790cc79f150/CPAC/registration/utils.py#L501-L531
https://github.com/FCP-INDI/C-PAC/blob/10f1d4d728bb0d9f5d530de8ab8a5790cc79f150/CPAC/registration/registration.py#L3752-L3766
