### ISSUE TITLE
🐛 `dc(bold2template_mask, template_mask)` `ValueError: operands could not be broadcast together with shapes (196,234,198) (182,218,182)`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1706]
### Describe the bug

> Some crashes to resolve @ 0f335db, like:
> 
> ```Python
> Node: cpac_sub-colornest035_ses-1.qcxcp_222
> Working directory: /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/qcxcp_222
> 
> Node inputs:
> 
> bold2t1w_mask = <undefined>
> bold2template_mask = <undefined>
> censor_indices = []
> desc = preproc
> dvars = <undefined>
> dvars_after = <undefined>
> fdj_after = <undefined>
> final_func = <undefined>
> framewise_displacement_jenkinson = <undefined>
> function_str = CPAC.qc.xcp.generate_xcp_qc
> movement_parameters = <undefined>
> original_func = <undefined>
> t1w_mask = <undefined>
> template = <undefined>
> template_mask = <undefined>
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 388, in run
>     return super().run(updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
>     runtime = self._run_interface(runtime)
>   File "/code/CPAC/utils/interfaces/function/function.py", line 152, in _run_interface
>     out = function_handle(**args)
>   File "/code/CPAC/qc/xcp.py", line 298, in generate_xcp_qc
>     template_mask=template_mask)
>   File "/code/CPAC/qc/qcmetrics.py", line 15, in regisQ
>     'normDice': [dc(bold2template_mask, template_mask)],
>   File "/code/CPAC/qc/qcmetrics.py", line 61, in dc
>     intersection = np.count_nonzero(input1 & input2)
> ValueError: operands could not be broadcast together with shapes (196,234,198) (182,218,182) 
> ```
> 
> ---
> 
> `/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/qcxcp_222/_report/report.rst`:
> > Node: qcxcp_222 (interfaces)
> > ============================
> > 
> > 
> >  Hierarchy : cpac_sub-colornest035_ses-1.qcxcp_222
> >  Exec ID : qcxcp_222.a0
> > 
> > 
> > Original Inputs
> > ---------------
> > 
> > 
> > * bold2t1w_mask : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/binarize_bold_to_T1w_mask_222/uni_masked_flirt_maths.nii.gz
> > * bold2template_mask : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz
> > * censor_indices : []
> > * desc : preproc
> > * dvars : /outputs/working/cpac_sub-colornest035_ses-1/gen_motion_stats_111/_scan_rest_run-01/cal_DVARS_strip/dvars_strip.1D
> > * dvars_after : /outputs/working/cpac_sub-colornest035_ses-1/motion_stats-after_222/_scan_rest_run-01/cal_DVARS_strip/dvars_strip.1D
> > * fdj_after : /outputs/working/cpac_sub-colornest035_ses-1/motion_stats-after_222/_scan_rest_run-01/calculate_FDJ/FD_J.1D
> > * final_func : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/func_extract_brain_107/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc_despike_tshift_resample_calc.nii.gz
> > * framewise_displacement_jenkinson : /outputs/working/cpac_sub-colornest035_ses-1/gen_motion_stats_111/_scan_rest_run-01/calculate_FDJ/FD_J.1D
> > * function_str : CPAC.qc.xcp.generate_xcp_qc
> > * movement_parameters : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/oned_concat_86/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc.1D
> > * original_func : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds/inputs/data/.git/annex/objects/VJ/5F/MD5E-s43982431--4505293d1740413480db269995b35cf6.nii.gz/MD5E-s43982431--4505293d1740413480db269995b35cf6.nii.gz
> > * space_T1w_bold : /outputs/working/cpac_sub-colornest035_ses-1/func_to_anat_bbreg_124/_scan_rest_run-01/bbreg_func_to_anat/uni_masked_flirt.nii.gz
> > * t1w_mask : /outputs/working/cpac_sub-colornest035_ses-1/anat_skullstrip_ants/atropos_wf/copy_xform/09_relabel_wm_mask_xform.nii.gz
> > * template : /outputs/working/cpac_sub-colornest035_ses-1/resampled_T1w-brain-template-funcreg/T1w-brain-template-funcreg/tpl-MNI152NLin2009cAsym_res-02_T1w_reference_resample.nii.gz
> > * template_mask : /usr/share/data/fsl-mni152-templates/MNI152_T1_1mm_brain_mask.nii.gz
> > 
> 
> ---
> 
> I thought maybe something was going wrong with resampling bold to T1w, but it looks okay to me:
> 
> `/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/_report/report.rst`:
> > Node: resample_bold_to_T1w_mask_222 (afni)
> > ==========================================
> > 
> > 
> >  Hierarchy : cpac_sub-colornest035_ses-1.resample_bold_to_T1w_mask_222
> >  Exec ID : resample_bold_to_T1w_mask_222.a0
> > 
> > 
> > Original Inputs
> > ---------------
> > 
> > 
> > * args : <undefined>
> > * environ : {}
> > * in_file : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz
> > * master : <undefined>
> > * num_threads : 1
> > * orientation : <undefined>
> > * out_file : <undefined>
> > * outputtype : NIFTI_GZ
> > * resample_mode : NN
> > * voxel_size : (1.0, 1.0, 1.0)
> > 
> > 
> > Execution Inputs
> > ----------------
> > 
> > 
> > * args : <undefined>
> > * environ : {}
> > * in_file : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz
> > * master : <undefined>
> > * num_threads : 1
> > * orientation : <undefined>
> > * out_file : <undefined>
> > * outputtype : NIFTI_GZ
> > * resample_mode : NN
> > * voxel_size : (1.0, 1.0, 1.0)
> > 
> > 
> > Execution Outputs
> > -----------------
> > 
> > 
> > * out_file : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz
> > 
> > 
> > Runtime info
> > ------------
> > 
> > 
> > * cmdline : 3dresample -prefix ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz -rmode NN -dxyz 1.000000 1.000000 1.000000 -inset /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz
> > * cpu_percent : 132.8
> > * duration : 0.670881
> > * hostname : 2115fmn032
> > * mem_peak_gb : 0.25716781640625
> > * prev_wd : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds
> > * working_dir : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222
> > 
> > 
> > Terminal output
> > ~~~~~~~~~~~~~~~
> > 
> > 
> >  
> > 
> > 
> > Terminal - standard output
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 
> > 
> >  
> > 
> > 
> > Terminal - standard error
> > ~~~~~~~~~~~~~~~~~~~~~~~~~
> > 
> > 
> >  ** AFNI converts NIFTI_datatype=64 (FLOAT64) in file /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz to FLOAT32
> >      Warnings of this type will be muted for this session.
> >      Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
> > 
> > 
> > Environment
> > ~~~~~~~~~~~
> > 
> > 
> > * ANTSPATH : /usr/lib/ants
> > * C3DPATH : /opt/c3d/
> > * FIX_VERTEX_AREA : 
> > * FREESURFER_HOME : /usr/lib/freesurfer
> > * FSFAST_HOME : /usr/lib/freesurfer/fsfast
> > * FSF_OUTPUT_FORMAT : nii.gz
> > * FSLBROWSER : /etc/alternatives/x-www-browser
> > * FSLDIR : /usr/share/fsl/5.0
> > * FSLLOCKDIR : 
> > * FSLMACHINELIST : 
> > * FSLMULTIFILEQUIT : TRUE
> > * FSLOUTPUTTYPE : NIFTI_GZ
> > * FSLREMOTECALL : 
> > * FSLTCLSH : /usr/bin/tclsh
> > * FSLWISH : /usr/bin/wish
> > * FSL_BIN : /usr/share/fsl/5.0/bin
> > * FSL_DIR : /usr/share/fsl/5.0
> > * FS_OVERRIDE : 0
> > * FUNCTIONALS_DIR : /usr/lib/freesurfer/sessions
> > * HOME : /cbica/projects/RBC
> > * ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS : 1
> > * KMP_DUPLICATE_LIB_OK : True
> > * KMP_INIT_AT_FORK : FALSE
> > * LANG : C
> > * LC_ALL : en_US.UTF-8
> > * LD_LIBRARY_PATH : /usr/lib/fsl/5.0::/.singularity.d/libs
> > * LOCAL_DIR : /usr/lib/freesurfer/local
> > * MINC_BIN_DIR : /usr/lib/freesurfer/mni/bin
> > * MINC_LIB_DIR : /usr/lib/freesurfer/mni/lib
> > * MKL_NUM_THREADS : 1
> > * MNI_DATAPATH : /usr/lib/freesurfer/mni/data
> > * MNI_DIR : /usr/lib/freesurfer/mni
> > * MNI_PERL5LIB : /usr/lib/freesurfer/mni/share/perl5
> > * MSMBINDIR : /opt/msm/Ubuntu
> > * NIPYPE_NO_ET : 1
> > * NO_FSFAST : 1
> > * OMP_NUM_THREADS : 1
> > * OS : Linux
> > * PATH : /usr/lib/freesurfer/bin:/usr/lib/freesurfer/fsfast/bin:/usr/lib/freesurfer/tktools:/usr/share/fsl/5.0/bin:/usr/lib/fsl/5.0:/usr/lib/freesurfer/mni/bin:/usr/lib/freesurfer/bin:/usr/local/miniconda/bin:/opt/ICA-AROMA:/usr/lib/ants:/opt/afni:/opt/c3d//bin:/root/.npm-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/msm/Ubuntu
> > * PERL5LIB : /usr/lib/freesurfer/mni/share/perl5
> > * POSSUMDIR : /usr/share/fsl/5.0
> > * PROMPT_COMMAND : PS1="Singularity> "; unset PROMPT_COMMAND
> > * PWD : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds
> > * SHLVL : 1
> > * SINGULARITY_APPNAME : 
> > * SINGULARITY_BIND : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds,/cbica/comp_space/RBC/job-59323-sub-colornest035/ds/sub-colornest035_outputs:/outputs
> > * SINGULARITY_COMMAND : run
> > * SINGULARITY_CONTAINER : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds/pennlinc-containers/.datalad/environments/cpac-1-8-4-dev/image
> > * SINGULARITY_ENVIRONMENT : /.singularity.d/env/91-environment.sh
> > * SINGULARITY_NAME : image
> > * SUBJECTS_DIR : /usr/lib/freesurfer/subjects
> > * TERM : 
> > * _ : /code/run.py
> > 
> 
> ---
> 
> And the voxel size matches but the dimensions don't:
> ```Python
> >>> import nibabel as nib
> >>> bold2template_mask = nib.load('/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz')
> >>> template_mask = nib.load('/usr/share/data/fsl-mni152-templates/MNI152_T1_1mm_brain_mask.nii.gz')
> >>> bold2template_mask.shape
> (196, 234, 198)
> >>> template_mask.shape
> (182, 218, 182)
> >>> print(bold2template_mask.header.get_zooms())
> (1.0, 1.0, 1.0)
> >>> print(template_mask.header.get_zooms())
> (1.0, 1.0, 1.0)
> ```
> 
> ---
> [cpac_pipeline_config_2022-03-30T21-13-38Z.yml](https://github.com/FCP-INDI/C-PAC/files/8412943/cpac_pipeline_config_2022-03-30T21-13-38Z.yml.txt)

_Originally posted by @shnizzedy in https://github.com/FCP-INDI/C-PAC/issues/1683#issuecomment-1084677341_

> Closer @ cfc6f93:
> 
> ```Python
> Node: cpac_sub-colornest001_ses-1.qcxcp_205
> Working directory: /data3/cnl/jclucas/UPenn/maxrun/working/cpac_sub-colornest001_ses-1/_scan_rest_run-02/qcxcp_205
> 
> Node inputs:
> 
> bold2t1w_mask = <undefined>
> bold2template_mask = <undefined>
> censor_indices = []
> desc = preproc
> dvars = <undefined>
> dvars_after = <undefined>
> fdj_after = <undefined>
> final_func = <undefined>
> framewise_displacement_jenkinson = <undefined>
> function_str = CPAC.qc.xcp.generate_xcp_qc
> movement_parameters = <undefined>
> original_func = <undefined>
> t1w_mask = <undefined>
> template = <undefined>
> template_mask = <undefined>
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 377, in run
>     return super().run(updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
>     runtime = self._run_interface(runtime)
>   File "/code/CPAC/utils/interfaces/function/function.py", line 152, in _run_interface
>     out = function_handle(**args)
>   File "/code/CPAC/qc/xcp.py", line 298, in generate_xcp_qc
>     template_mask=template_mask)
>   File "/code/CPAC/qc/qcmetrics.py", line 15, in regisQ
>     'normDice': [dc(bold2template_mask, template_mask)],
>   File "/code/CPAC/qc/qcmetrics.py", line 61, in dc
>     intersection = np.count_nonzero(input1 & input2)
> ValueError: operands could not be broadcast together with shapes (196,234,198) (193,229,193)
> ```

_Originally posted by @shnizzedy in https://github.com/FCP-INDI/C-PAC/issues/1683#issuecomment-1091732704_

### To reproduce

Run with 

```YAML
pipeline_setup:
  output_directory:
    quality_control:
      generate_xcpqc_files: On
```

at cfc6f93

### Expected behavior

`bold2template_mask` and `template_mask` are the same shape

### Acceptance criteria

- [x] `bold2template_mask` and `template_mask` are the same shape

### C-PAC version

v1.8.4-dev @ cfc6f93

### Container platform

Docker, Singularity

**Comment by shnizzedy** [comment]
Resolved in e6332bb
