### ISSUE TITLE
🐛 Error in building group config file by `cpac group feat load_preset`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1719]
### Discussed in https://github.com/FCP-INDI/C-PAC/discussions/1712

<div type='discussions-op-text'>

<sup>Originally posted by **Zeigar** April 19, 2022</sup>
Hi everyone,

After preprocessed by “cpac run”, I am trying to generate model presets in different way but always get errors. Following the online user guide, the output of “cpac group feat load_preset single_grp_avg --help” is:
Usage: run.py group feat load_preset single_grp_avg [OPTIONS] PIPELINE_DIR
                                                    Z_THRESH P_THRESH
                                                    MODEL_NAME
So, the command “_cpac group feat load_preset single_grp_avg /home/user/Test/cpac/output 2.3 0.05 sgl_sub4_” was executed, but it failed to access the “**cpac_outputs.csv**” file. Moreover, the command “_cpac group feat build_models /home/user/Applications/cpac/group_config_sharp.yml_” had the same error. The detailed error is as follows: 

```
raceback (most recent call last):
  File "/code/CPAC/utils/create_fsl_flame_preset.py", line 998, in run
    keys = pd.read_csv(keys_csv)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/code/CPAC/resources/cpac_outputs.csv' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/run.py", line 762, in <module>
    run_main()
  File "/code/run.py", line 334, in run_main
    main.main(args=sys.argv[sys.argv.index('--') + 1:])
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  [Previous line repeated 1 more time]
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/code/CPAC/__main__.py", line 176, in single_grp_avg
    model_name=model_name)
  File "/code/CPAC/utils/create_fsl_flame_preset.py", line 1002, in run
    raise Exception(err)
Exception: 
[!] Could not access or read the cpac_outputs.csv resource file:
/code/CPAC/resources/cpac_outputs.csv

Error details File b'/code/CPAC/resources/cpac_outputs.csv' does not exist
```

Thanks a lot,
Xiaochen
</div>

**Comment by nimzodisaster** [comment]
I have this error too in data preprocessed in 1.8.4 and I really would like to run some analyses for a conference. Options?

**Comment by augustoielo** [comment]
I get the same error running "cpac group feat load-preset paired-two" after the default CPAC pipeline.

`Error details [Errno 2] No such file or directory: '/code/CPAC/resources/cpac_outputs.csv'. `

Any ideas on how to bypass the problem and perform the analysis? Thanks.
