### ISSUE TITLE
🐛 Eigenvector Centrality Binarized needs additional flag

### ISSUE THREAD

**Issue by amygutierrez** [FCP-INDI/C-PAC#1807]
### Describe the bug

When using AFNI version: AFNI_22.1.14, `3dECM` only creates 1 subbrik instead of 2 subbriks (one for weighted and one for binarized). 

The default for [3dECM](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dECM.html) solves for weighted ECM. To solve for binarized ECM, you have to add flag`-do_binary`. 

If options if both `[Binarized, Weighted]` like in [benchmark-FNIRT](https://github.com/FCP-INDI/C-PAC/blob/9586d7146eff224200e18622523a56da6a9826a6/CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml#L235), then you need to run node without flag and then with flag `-do_binary`. 

This also means that output for node does not need to be separated [here](https://github.com/FCP-INDI/C-PAC/blob/9586d7146eff224200e18622523a56da6a9826a6/CPAC/network_centrality/utils.py#L86-L117). 

### To reproduce

run cpac with preconfig **benchmark-FNIRT**
Example:
```
docker run --security-opt=apparmor:unconfined --rm -v /Users/amy.gutierrez/Documents/Debug/Data/Site-RU:/data -v /Users/amy.gutierrez/Documents/benchmark-FNIRT:/output fcpindi/c-pac:nightly /data /output participant --save_working_dir --skip_bids_validator --n_cpus 1 --mem_gb 15 --participant_label sub-NDARAE270LEZ --preconfig benchmark-FNIRT
```

This will produce following crash files with error:
```
  File "<string>", line 20, in sep_nifti_subbriks
Exception: out_names must have same number of elements as nifti sub-briks
```

### Preconfig

- [ ] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Run command

```
docker run --security-opt=apparmor:unconfined --rm -v /Users/amy.gutierrez/Documents/Debug/Data/Site-RU:/data -v /Users/amy.gutierrez/Documents/benchmark-FNIRT:/output fcpindi/c-pac:nightly /data /output participant --save_working_dir --skip_bids_validator --n_cpus 1 --mem_gb 15 --participant_label sub-NDARAE270LEZ --preconfig benchmark-FNIRT
```

### Expected behavior

Will output crash file like below: 
```
Node: cpac_sub-NDARAV894XWD_1.afni_centrality_eigenvector_centrality_658.sep_nifti_subbriks
Working directory: /ocean/projects/med220004p/agutierr/reg_test_1.8.4/fixed_seed/benchmark-FNIRT/Site-SI/working/cpac_sub-NDARAV894XWD_1/afni_centrality_eigenvector_centrality_658/_scan_task-rest/sep_nifti_subbriks

Node inputs:

function_str = def sep_nifti_subbriks(nifti_file, out_names):
    '''
    '''
    import os
    import nibabel as nib

    output_niftis = []

    nii_img = nib.load(nifti_file)
    nii_arr = nii_img.get_data()
    nii_affine = nii_img.get_affine()
    nii_dims = nii_arr.shape

    if nii_dims[-1] != len(out_names):
        if len(nii_dims) == 3 and len(out_names) == 1:
            pass
        else:
            err_msg = 'out_names must have same number of elements as '\
                      'nifti sub-briks'
            raise Exception(err_msg)

    for brik, out_name in enumerate(out_names):
        if len(nii_dims) == 3:
            brik_arr = nii_arr
        elif len(nii_dims) > 3:
            brik_arr = nii_arr[:, :, :, 0, brik]
        out_file = os.path.join(os.getcwd(), out_name+'.nii.gz')
        out_img = nib.Nifti1Image(brik_arr, nii_affine)
        out_img.to_filename(out_file)
        output_niftis.append(out_file)

    return output_niftis

nifti_file = <undefined>
out_names = ('eigenvector_centrality_Binarized', 'eigenvector_centrality_Weighted')

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 406, in run
    return super().run(updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 20, in sep_nifti_subbriks
Exception: out_names must have same number of elements as nifti sub-briks
```

Nifti file `eigenvector_centrality_merged.nii.gz` will only have 1 subbrik called `ecm weighted`. Can check this with `3dinfo`

### Acceptance criteria

All centrality methods should output with respective weighted options (weighted or binarized). 

### C-PAC version

v1.8.4

### Additional context

Must test with AFNI version AFNI_22.1.14 or greater.

**Comment by amygutierrez** [comment]
Issue has been fixed in PR  #1791
