### ISSUE TITLE
🐛 [User-reported Bug] Missing default yml in v1.8.5 Docker Image

### ISSUE THREAD

**Issue by tjlagrow** [FCP-INDI/C-PAC#1951]
### Describe the bug

Last week I was able to run CPAC without a hitch. When I go to rerun some scans, I am getting a new issue that the default_config.yml is not in the latest image of cpac from dockerhub. I will post my error below. I have double and triple checked there is nothing wrong with my python installation or docker installation. I am curious if anyone else is having these issues. I needed to go back to the v1.8.4 release of CPAC's docker image to attempt to run something, however I am significantly slower to almost a standstill. Any help with this issue is most welcome. 

### To reproduce

After much troubleshooting, I tried to start from scratch. 

1. Fresh installation of Ubuntu
2. Follow instructions to download Docker Engine from website (https://docs.docker.com/engine/install/)
3. Install CPAC via commmandline pip
4. Run the following line of code: 

sudo cpac run /home/tjlagrow/Documents/ADNI/sNC_f/bids_dir /home/tjlagrow/Documents/ADNI/sNC_f/outputs test_config

I receive the following error: 

Loading 🐳 Docker
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/47e44403e2685989363deadd3600432d36dddf442e67e085f428aeff9dffa8e9/archive?path=%2Fcpac_resources%2Fdefault_pipeline.yml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/cpac", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/cpac/__main__.py", line 452, in run
    main(parsed)
  File "/usr/local/lib/python3.10/dist-packages/cpac/__main__.py", line 339, in main
    Backends(**arg_vars).run(
  File "/usr/local/lib/python3.10/dist-packages/cpac/backends/__init__.py", line 24, in Backends
    {
  File "/usr/local/lib/python3.10/dist-packages/cpac/backends/docker.py", line 35, in __init__
    self._collect_config(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cpac/backends/docker.py", line 71, in _collect_config
    stream = container.get_archive(path=self.pipeline_config)[0]
  File "/usr/local/lib/python3.10/dist-packages/docker/models/containers.py", line 262, in get_archive
    return self.client.api.get_archive(self.id, path,
  File "/usr/local/lib/python3.10/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/container.py", line 761, in get_archive
    self._raise_for_status(res)
  File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.10/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/47e44403e2685989363deadd3600432d36dddf442e67e085f428aeff9dffa8e9/archive?path=%2Fcpac_resources%2Fdefault_pipeline.yml: Not Found ("Could not find the file /cpac_resources/default_pipeline.yml in container 47e44403e2685989363deadd3600432d36dddf442e67e085f428aeff9dffa8e9")

### Preconfig

- [X] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [X] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

default (doesn't seem to exist in the image....)

### Run command

sudo cpac run /home/tjlagrow/Documents/ADNI/sNC_f/bids_dir /home/tjlagrow/Documents/ADNI/sNC_f/outputs test_config --platform docker

### Expected behavior

The default docker image to be set up properly where the test_config command to work and work fast.

### Acceptance criteria

Verification that the default_pipeline.yml file exists in the image. Did it get moved?

### C-PAC version

v1.8.5

### Container platform

Docker

**Comment by amygutierrez** [comment]
Hello, 
Thank you for bringing this to our attention. Maybe you can try adding the flag `--preconfig default` and see if that helps. So your command would look like 
```
sudo cpac run /home/tjlagrow/Documents/ADNI/sNC_f/bids_dir /home/tjlagrow/Documents/ADNI/sNC_f/outputs test_config --platform docker --preconfig default
```

Please let me know if that helps or of any other error arises.

**Comment by tjlagrow** [comment]
Thank you for the prompt response, I appreciated it! 
I was able to use the latest docker image when using the `--preconfig default` flag. However, I am still running into the same issue of virtually no processing. This was not an issue previously and I am unsure what to do to help correct this. I did several tests both on my system and docker for both ram health and harddrive health - both are healthy. I also attempted a fresh install of Ubuntu 20.04 LTS to no added benefit. Is there maybe something else I'm missing?

Previously, I was able to use the test_config command and the process would finish in under a minute. With the new update, the process is hanging up for minutes on each nipype.workflow process. I have tried a great number of times and I have still yet to complete one subject using test_config. I will post one of my run's output. I am trying to use the test_config command on 3 HCP participants, each with 4 scans. I expect 12 outputs but after 15 minutes, I have yet to get through 1 scan of "connecting...".
[cpac_docker_processing_issue.txt](https://github.com/FCP-INDI/C-PAC/files/11692537/cpac_docker_processing_issue.txt)

Additionally, when I process a bids directory, the overarching data_config and file pipeline_config are generated for each subject AND scan, generating quite a lot of redundancy. 

Please let me know if you need any further information.

**Comment by tjlagrow** [comment]
I was able to get through 1 scan with the output log ([pypeline.log](https://github.com/FCP-INDI/C-PAC/files/11696867/pypeline.log)). What took usually under a minute is now taking over 3 hours. I am a little lost on what is going on here or if I need to update a specific package in the docker image (nipype?) or if something else locally is going on? I stopped the process since this is just a `test_config` run. I took another scan I've run before and I'm trying to run the `participant ` command. I will report back if there is an issue with the processing when the initial `nipype.workflow connecting *...` finishes. 

I am now running:
`sudo cpac -vv run /home/tjlagrow/Documents/hcp_data/bids_dir_small /home/tjlagrow/Documents/hcp_data/outputs participant --platform docker --preconfig default \
--data_config_file /home/tjlagrow/Documents/hcp_data/outputs/cpac_data_config_99fd7508_2023-06-08T15-31-42Z.yml \
--pipeline_config_file /home/tjlagrow/Documents/hcp_data/outputs/cpac_pipeline_config_99fd7508_2023-06-08T15-31-42Z.yml \
--mem_gb 60.0 --n_cpus 16 `

**Comment by amygutierrez** [comment]
Thank you for your detailed comments! I was able to run your command on my system without any hanging issues or redundancy issues (Ubuntu 18.04.1 LTS). 
Are you still using the latest version of CPAC (v1.8.5)? To upgrade the version, you can do `cpac --platform docker --tag latest pull` and you can also add `--tag latest` in your cpac run command to ensure you are using the latest version. 
Also, can you show maybe a tree of how your bids directory looks like? I can try mimicking it to see if I run into the same issue.

**Comment by tjlagrow** [comment]
Thank you for your quick comments!
I am unsure what changed but I was able to run the processes on two systems on different linux distros (Ubuntu 20.04 LTS and CentOS) without a processing issues. This was true for both CPAC v1.8.4 and v1.8.5. I am not sure why it fixed the issue, but using `sudo python3 -m cpac ...` ended up doing the trick. I am not sure if it was a pathing issue for specific packages but that shouldn't be the case with the dockerized code. 

In terms of a file structure, attached is a printout. This is the result of `ls -R` which is a little messy. 
[file_structure.txt](https://github.com/FCP-INDI/C-PAC/files/11727466/file_structure.txt)

**Comment by shnizzedy** [comment]
@tjlagrow I'm glad you were able to get `cpac` to run. The issue here I believe is just a little asynchrony in the release cycles of the various C-PAC packages ― C-PAC itself v1.8.5 is available, but the latest version's documentation isn't locked yet, and [the changes necessary for the `cpac` convenience wrapper to work seamlessly with v1.8.5](https://github.com/FCP-INDI/cpac/pull/36) are not yet merged / released / published. 

In case anyone finds this issue when C-PAC is ahead of cpac and the docs, [the nightly documentation for running directly in Docker](https://fcp-indi.github.io/docs/nightly/user/docker) or [in Singularity](https://fcp-indi.github.io/docs/nightly/user/singularity) is another way to run the latest (or nightly) image when `cpac` isn't yet supporting that version. Or if you aren't necessarily wanting to use the bleeding edge version, you can specify [a less-recent version](https://fcp-indi.github.io/docs/nightly/user/versions) [`--tag`](https://fcp-indi.github.io/docs/nightly/user/running#usage) like 

```BASH
cpac --tag release-v1.8.4 run /home/tjlagrow/Documents/ADNI/sNC_f/bids_dir /home/tjlagrow/Documents/ADNI/sNC_f/outputs test_config
```

to run the second-most-recent version of C-PAC (the most recent version currently supported by `cpac`)

Duplicate of https://github.com/FCP-INDI/cpac/issues/35
