### ISSUE TITLE
Crash at Centrality measures

### ISSUE THREAD

**Issue by petergoodin** [FCP-INDI/C-PAC#395]
Hi, 

I'm having some problems with getting centrality measures output. Specifically it crashes at the histogram and montage stages (please see below) and possibly due to a problem with the backend in use - I get the following error message on importing CPAC: 

/usr/lib/pymodules/python2.7/matplotlib/**init**.py:1173: UserWarning:  This call to matplotlib.use() has no effect because the backend has already been chosen;
matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

Any advice would be greatly appreciated. 

```
                            Histogram crash log: 
```

Traceback (most recent call last):\n'

 File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node\n    result[\'result\'] = node.run(updatehash=updatehash)\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1424, in run\n    self._run_interface()\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1534, in _run_interface\n    self._result = self._run_command(execute)\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1660, in _run_command\n    result = self._interface.run()\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 998, in run\n    runtime = self._run_interface(runtime)\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/utility.py", line 436, in _run_interface\n    out = function_handle(**args)\n'

File "<string>", line 67, in gen_histogram\n'

File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 1715, in make_histogram\n    fig = pyplot.figure()\n'

File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure\n    **kwargs)\n'

File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager\n    return new_figure_manager_given_figure(num, figure)\n'

File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 96, in new_figure_manager_given_figure\n    icon_img = Tk.PhotoImage(file=icon_fname)\n'

File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3329, in **init**\n    Image.**init**(self, \'photo\', name, cnf, master, **kw)\n'

File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3285, in **init**\n    self.tk.call((\'image\', \'create\', imgtype, name,) + options)\n'

'RuntimeError: main thread is not in main loop\nInterface Function failed to run. \n'

```
                    Montage crash log: 
```

Traceback (most recent call last):\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node\n    result[\'result\'] = node.run(updatehash=updatehash)\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1424, in run\n    self._run_interface()\n'

 File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1534, in _run_interface\n    self._result = self._run_command(execute)\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1660, in _run_command\n    result = self._interface.run()\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 998, in run\n    runtime = self._run_interface(runtime)\n'

File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/utility.py", line 436, in _run_interface\n    out = function_handle(**args)\n'

 File "<string>", line 36, in montage_axial\n'

 File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 2043, in make_montage_axial\n    fig = plt.figure(1)\n'

 File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure\n    **kwargs)\n'

File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager\n    return new_figure_manager_given_figure(num, figure)\n'

  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 96, in new_figure_manager_given_figure\n    icon_img = Tk.PhotoImage(file=icon_fname)\n'

 File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3329, in **init**\n    Image.**init**(self, \'photo\', name, cnf, master, **kw)\n'

 File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3285, in **init**\n    self.tk.call((\'image\', \'create\', imgtype, name,) + options)\n'

RuntimeError: main thread is not in main loop\nInterface Function failed to run. \n'

**Comment by sgiavasis** [comment]
FYI - QC interface was fixed and reintroduced in C-PAC v1.1.
