### ISSUE TITLE
Give warning if data isn't organized according to BIDS but 'Data format' is set to BIDS

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#577]
With the attached data configuration file, I was able to produce the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 183, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 381, in save
    if self.run(path) >0:
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 250, in run
    CPAC.utils.build_sublist.build_sublist(config)
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/utils/build_sublist.py", line 783, in build_sublist
    anat_template = return_bids_template(bids_base_dir, 'anat')
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/utils/build_sublist.py", line 658, in return_bids_template
    if base_dir.startswith(s3_str):
AttributeError: 'list' object has no attribute 'startswith'
```

This occurs if a custom format dataset is input but 'BIDS' is still selected as the option for 'Data format' with 'BIDS base directory' empty.  It would be better to present users with a warning if they accidentally do this.

[data_config_template_wrong_bids_setting.txt](https://github.com/FCP-INDI/C-PAC/files/576777/data_config_template_wrong_bids_setting.txt)

**Comment by sgiavasis** [comment]
I have included checks for these, as well as additional needed checks for the custom filepath template fields.

**Comment by jpellman** [comment]
I'm getting an error dialog telling me to use 'Custom' instead of 'BIDS' so this is resolved.
