### ISSUE TITLE
ValueError: '{participant}' is not in list due to combining tags and literal strings

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#614]
I'm getting the following error with the attached data config (data_config_bidssub.txt):

```
saving /tmp/data_config_bidssub.txt
Gathering anatomical files...
2016-12-05 16:34:02,007 : Found 13 files!
2016-12-05 16:34:02,007 : Found 13 files!
2016-12-05 16:34:02,007 : Found 13 files!
2016-12-05 16:34:02,007 : Found 13 files!
2016-12-05 16:34:02,007 : Found 13 files!
161205-16:34:02,7 sublist_builder INFO:
	 Found 13 files!
Gathering functional files...
2016-12-05 16:34:02,013 : Found 13 files!
2016-12-05 16:34:02,013 : Found 13 files!
2016-12-05 16:34:02,013 : Found 13 files!
2016-12-05 16:34:02,013 : Found 13 files!
2016-12-05 16:34:02,013 : Found 13 files!
161205-16:34:02,13 sublist_builder INFO:
	 Found 13 files!
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac101_120116/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 183, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
  File "/usr/local/bin/miniconda/envs/cpac101_120116/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 445, in save
    if self.run(path) >0:
  File "/usr/local/bin/miniconda/envs/cpac101_120116/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 250, in run
    CPAC.utils.build_sublist.build_sublist(config)
  File "/usr/local/bin/miniconda/envs/cpac101_120116/lib/python2.7/site-packages/CPAC/utils/build_sublist.py", line 848, in build_sublist
    return_dir_indices(anat_template)
  File "/usr/local/bin/miniconda/envs/cpac101_120116/lib/python2.7/site-packages/CPAC/utils/build_sublist.py", line 470, in return_dir_indices
    ppant_idx = fp_split.index('{participant}')
ValueError: '{participant}' is not in list
```
[data_config_bidssub.txt](https://github.com/FCP-INDI/C-PAC/files/632335/data_config_bidssub.txt)

I suspect it's due to combining a string with a tag ('sub-' + '{participant}'), so I tested it out with a different template with out the string and it worked (see below).

[data_config_bidssub_works.txt](https://github.com/FCP-INDI/C-PAC/files/632340/data_config_bidssub_works.txt)

If combining tags and strings isn't desirable behavior, we should make this clearer in the documentation and throw a warning to the user if they try to do this.

**Comment by sgiavasis** [comment]
But this is set to Custom- are you saying that there should be a warning if the user has a BIDS-like format that is a custom data format?

**Comment by jpellman** [comment]
The ability to glob datasets in BIDS using a custom template is less of an issue- if people know the BIDS option they're less likely to do that.  The main issue here is that someone might have their own custom format where they want to combine text and strings (it doesn't need to be BIDS-like necessarily).  If for instance someone used something like this:

{participant}_anat
{participant}_func

Where the anat and func directories for each participant are all in the root level, you'd still run into the same issue, since you'd be combining strings and tags to try to create templates to match that.

e.g.:
/home/johnpellman/Downloads/{site}/{participant}_anat/anat.nii.gz
/home/johnpellman/Downloads/{site}/{participant}_func/task.nii.gz

**Comment by sgiavasis** [comment]
Okay, I pushed the change to 1.0.1_development.

Points for testing:
- That it handles custom templates mentioned above (i.e. {participant}_anat, etc.).
- Multiple different keywords in one directory level (../{participant}_{session}/..)
- Multiple instances of the same keyword (../{participant}_anat/{participant}/...)
- That the BIDS data format still works!

**Comment by jpellman** [comment]
These all work.  One odd thing happened when I gave the subject list builder a BIDS base directory instead of a custom path for BIDS- I'll post that here:

https://github.com/FCP-INDI/C-PAC/issues/617
