### ISSUE TITLE
'alff_to_standard_smooth' not in resource pool when func-to-MNI off

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#637]
The  following error when assembling a pipeline in C-PAC 1.0.1 without MNI registration on:

```
ERROR: Invalid Connection: alff_to_standard_smooth z-score standardize: 0, resource_pool: 
{'anatomical_gm_mask': (resting_preproc_sub-A00028605_ses-DS2.seg_preproc_0, 
'outputspec.gm_mask'), 'falff_img': (resting_preproc_sub-A00028605_ses-DS2.alff_falff_0, 
'outputspec.falff_img'), 'scrubbing_frames_included': (resting_preproc_sub-A00028605_ses-
DS2.gen_motion_stats_0, 'outputspec.frames_in_1D'), 'functional_to_anat_linear_xfm': 
(resting_preproc_sub-A00028605_ses-DS2.func_to_anat_bbreg_0, 
'outputspec.func_to_anat_linear_xfm'), 'output_means.@falff_img_average': (resting_preproc_sub-
A00028605_ses-DS2.falff_img_mean_to_txt_0, 'output_mean'), 'anatomical_wm_mask': 
(resting_preproc_sub-A00028605_ses-DS2.seg_preproc_0, 'outputspec.wm_mask'), 
'functional_nuisance_regressors': (resting_preproc_sub-A00028605_ses-DS2.nuisance_0, 
'outputspec.regressors'), 'output_means.@alff_img_average': (resting_preproc_sub-A00028605_ses-
DS2.alff_img_mean_to_txt_0, 'output_mean'), 'anatomical_brain': (resting_preproc_sub-
A00028605_ses-DS2.anat_preproc_0, 'outputspec.brain'), 'seg_partial_volume_files': 
(resting_preproc_sub-A00028605_ses-DS2.seg_preproc_0, 'outputspec.partial_volume_files'), 
'movement_parameters': (resting_preproc_sub-A00028605_ses-DS2.fristons_parameter_model_0, 
'outputspec.movement_file'), 'seg_partial_volume_map': (resting_preproc_sub-A00028605_ses-
DS2.seg_preproc_0, 'outputspec.partial_volume_map'), 'max_displacement': (resting_preproc_sub-
A00028605_ses-DS2.func_preproc_automask_0, 'outputspec.max_displacement'), 
'scrubbing_movement_parameters': (resting_preproc_sub-A00028605_ses-DS2.scrubbing_0, 
'outputspec.scrubbed_movement_parameters'), 'seg_mixeltype': (resting_preproc_sub-A00028605_ses-
DS2.seg_preproc_0, 'outputspec.mixeltype'), 'mni_to_anatomical_nonlinear_xfm': (resting_preproc_sub-
A00028605_ses-DS2.anat_mni_ants_register_0, 'outputspec.inverse_warp_field'), 'ants_initial_xfm': 
(resting_preproc_sub-A00028605_ses-DS2.anat_mni_ants_register_0, 'outputspec.ants_initial_xfm'), 
'mean_functional': (resting_preproc_sub-A00028605_ses-DS2.func_preproc_automask_0, 
'outputspec.example_func'), 'functional_preprocessed_mask': (resting_preproc_sub-A00028605_ses-
DS2.func_preproc_automask_0, 'outputspec.preprocessed_mask'), 'alff_img': (resting_preproc_sub-
A00028605_ses-DS2.alff_falff_0, 'outputspec.alff_img'), 'scrubbed_preprocessed': (resting_preproc_sub-
A00028605_ses-DS2.scrubbing_0, 'outputspec.preprocessed'), 'output_means.@falff_smooth_average': 
(resting_preproc_sub-A00028605_ses-DS2.falff_smooth_mean_to_txt_0, 'output_mean'), 
'frame_wise_displacement': (resting_preproc_sub-A00028605_ses-DS2.gen_motion_stats_0, 
'outputspec.FD_1D'), 'raw_functional': (resting_preproc_sub-A00028605_ses-DS2.func_gather_0, 
'outputspec.rest'), 'seg_probability_maps': (resting_preproc_sub-A00028605_ses-DS2.seg_preproc_0, 
'outputspec.probability_maps'), 'alff_smooth': (resting_preproc_sub-A00028605_ses-DS2.alff_smooth_0,
 'out_file'), 'raw_reho_map': (resting_preproc_sub-A00028605_ses-DS2.reho_0, 
'outputspec.raw_reho_map'), 'functional_freq_filtered': (resting_preproc_sub-A00028605_ses-
DS2.frequency_filter_0, 'bandpassed_file'), 'ants_rigid_xfm': (resting_preproc_sub-A00028605_ses-
DS2.anat_mni_ants_register_0, 'outputspec.ants_rigid_xfm'), 'anatomical_csf_mask': 
(resting_preproc_sub-A00028605_ses-DS2.seg_preproc_0, 'outputspec.csf_mask'), 
'anat_to_mni_ants_composite_xfm': (resting_preproc_sub-A00028605_ses-
DS2.anat_mni_ants_register_0, 'outputspec.composite_transform'), 'scrubbing_frames_excluded': 
(resting_preproc_sub-A00028605_ses-DS2.gen_motion_stats_0, 'outputspec.frames_ex_1D'), 
'mean_functional_in_anat': (resting_preproc_sub-A00028605_ses-DS2.func_to_anat_bbreg_0, 
'outputspec.anat_func'), 'anatomical_to_mni_nonlinear_xfm': (resting_preproc_sub-A00028605_ses-
DS2.anat_mni_ants_register_0, 'outputspec.warp_field'), 'motion_correct': (resting_preproc_sub-
A00028605_ses-DS2.func_preproc_automask_0, 'outputspec.motion_correct'), 'ants_affine_xfm': 
(resting_preproc_sub-A00028605_ses-DS2.anat_mni_ants_register_0, 'outputspec.ants_affine_xfm'), 
'coordinate_transformation': (resting_preproc_sub-A00028605_ses-DS2.func_preproc_automask_0, 
'outputspec.oned_matrix_save'), 'functional_brain_mask': (resting_preproc_sub-A00028605_ses-
DS2.func_preproc_automask_0, 'outputspec.mask'), 'falff_smooth': (resting_preproc_sub-
A00028605_ses-DS2.falff_smooth_0, 'out_file'), 'preprocessed': (resting_preproc_sub-A00028605_ses-
DS2.func_preproc_automask_0, 'outputspec.preprocessed'), 'slice_time_corrected': 
(resting_preproc_sub-A00028605_ses-DS2.func_slice_timing_correction_0, 'out_file'), 
'functional_nuisance_residuals': (resting_preproc_sub-A00028605_ses-DS2.nuisance_0, 
'outputspec.subject'), 'motion_params': (resting_preproc_sub-A00028605_ses-DS2.gen_motion_stats_0,
'outputspec.motion_params'), 'anatomical_reorient': (resting_preproc_sub-A00028605_ses-
DS2.anat_preproc_0, 'outputspec.reorient'), 'power_params': (resting_preproc_sub-A00028605_ses-
DS2.gen_motion_stats_0, 'outputspec.power_params'), 'mni_normalized_anatomical': 
(resting_preproc_sub-A00028605_ses-DS2.anat_mni_ants_register_0, 
'outputspec.normalized_output_brain'), 'output_means.@alff_smooth_average': (resting_preproc_sub-
A00028605_ses-DS2.alff_smooth_mean_to_txt_0, 'output_mean')}

Error name: cpac_pipeline_0127

This is a pipeline creation error - the workflows have not started yet.


Process Process-2:
Traceback (most recent call last):
  File "/home2/jpellman/miniconda/envs/cpac101/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home2/jpellman/miniconda/envs/cpac101/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home2/jpellman/miniconda/envs/cpac101/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 4148, in prep_workflow
    z_score_standardize('alff_to_standard_smooth', 'alff_to_standard_smooth', strat, num_strat)
  File "/home2/jpellman/miniconda/envs/cpac101/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 3686, in z_score_standardize
    node, out_file = strat.get_node_from_resource_pool(output_resource)
  File "/home2/jpellman/miniconda/envs/cpac101/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 109, in get_node_from_resource_pool
    return self.resource_pool[resource_key]
KeyError: 'alff_to_standard_smooth'
```

There should be a more informative error message for this.

**Comment by sgiavasis** [comment]
This no longer happens, but I am seeing this:

```
Traceback (most recent call last):
  File "/code/run.py", line 588, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 344, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 2837, in prep_workflow
    node, out_file = strat['functional_to_standard']
  File "/code/CPAC/utils/strategy.py", line 57, in __getitem__
    return self.resource_pool[resource_key]
KeyError: 'functional_to_standard'
```
At some point, TSE and DR seems to have become dependent on the functional in template space. This is a bigger design question and will move this to either 1.6.2 or 1.7.
