### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by geowk** [FCP-INDI/C-PAC#652]
Hello, we are having trouble installing C-PAC. I think there is conflict with with python 2 or 3 dependencies during installation. We are pretty much lost at this point. Each time we try to run the final step in python2:

import CPAC

We keep getting error messages about missing modules that were installed successfully using conda.

Right now we are stuck at this error message:

Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python2.7/dist-packages/CPAC/init.py", line 21, in 
import anat_preproc, 
File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/init.py", line 3, in 
from cpac_pipeline import run
File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_pipeline.py", line 22, in 
from nipype.pipeline.engine.utils import format_dot
ImportError: No module named utils

Any help would greatly be appreciated.

Thanks.

d.m.

**Comment by sgiavasis** [comment]
Hi @geowk,

Sorry this hasn't been addressed- are you still having issues regarding this? Let us know and we can help.

Best,
Steve
