### ISSUE TITLE
Number of Cores per Subject configuration error

### ISSUE THREAD

**Issue by ntraut** [FCP-INDI/C-PAC#662]
Hello,
I set the pipeline configuration using the gui (using the `cpac_gui` command).
I could not validate the configuration because when I hit the `Test Configuration` I got the following error:
```
Traceback (most recent call last):
  File "/pasteur/homes/ntraut/anaconda3/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 570, in testConfig
    sub_flg = self.test_sublist(sublist)
  File "/pasteur/homes/ntraut/anaconda3/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 462, in test_sublist
    if func_file.lower().startswith(s3_str):
AttributeError: 'NoneType' object has no attribute 'lower'
```
But I guess it is a bug related to Issue #636 so I simply ignored it.

But when I tried to run CPAC for real by hitting the `Run Individual Level Analysis` button I got the following error:
```
Unhandled exception in thread started by <bound method ListBox.runAnalysis1 of <CPAC.GUI.interface.windows.main_window.ListBox; proxy of <Swig Object of type 'wxFrame *' at 0x4206990> >>
Traceback (most recent call last):
  File "/pasteur/homes/ntraut/anaconda3/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/main_window.py", line 240, in runAnalysis1
    plugin_args=plugin_args)
  File "/pasteur/homes/ntraut/anaconda3/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_runner.py", line 490, in run
    cluster_files_dir)
  File "/pasteur/homes/ntraut/anaconda3/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_runner.py", line 276, in run_cpac_on_cluster
    plugin_args = {'n_procs': pipeline_config.numCoresPerSubject,
AttributeError: 'Configuration' object has no attribute 'numCoresPerSubject'
```
The script is looking for a field named `numCoresPerSubject` in the pipeline configuration file but there is not, instead there is a field named `maxCoresPerParticipant`, so maybe the name has changed but the script has not been updated to the new name...

**Comment by sgiavasis** [comment]
Thank you for bringing this up!
