### ISSUE TITLE
pipeline output directory

### ISSUE THREAD

**Issue by florisvanvugt** [FCP-INDI/C-PAC#666]
Hi,

When I launch the group analysis and change the output directory, it gives me an error. I think this is an error of an error, where the error message doesn't seem to get properly formatted (`\s` is not a formatting mark in Python, but `%s` seems to do the job, as shown by my suggested changeset below).
Thanks

```
Gathering the output file paths from /brains/pianists/output/20170706_pipeline_pianists-3mm-fsl...
Unhandled exception in thread started by <bound method runGLA.runAnalysis of wxPython wrapper for DELETED runGLA object! (The C++ object no longer exists.)>
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/main_window.py", line 842, in runAnalysis
    CPAC.pipeline.cpac_group_runner.run(pipeline, path)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_group_runner.py", line 772, in run
    analysis_dict = prep_analysis_df_dict(config_file, pipeline_output_folder)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_group_runner.py", line 580, in prep_analysis_df_dict
    get_raw_score)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_group_runner.py", line 364, in gather_outputs
    nifti_globs = gather_nifti_globs(pipeline_folder, resource_list)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_group_runner.py", line 142, in gather_nifti_globs
    % (pipeline_output_folder, resource_list)
TypeError: not all arguments converted during string formatting
```

The error was solved on my system with the following change:

``` 
diff --git a/CPAC/pipeline/cpac_group_runner.py b/CPAC/pipeline/cpac_group_runner.py
index 79f4575..8f12991 100644
--- a/CPAC/pipeline/cpac_group_runner.py
+++ b/CPAC/pipeline/cpac_group_runner.py
@@ -138,7 +138,7 @@ def gather_nifti_globs(pipeline_output_folder, resource_list):
     if len(nifti_globs) == 0:
         err = "\n\n[!] No output filepaths found in the pipeline output " \
               "directory provided for the derivatives selected!\n\nPipeline "\
-              "output directory provided: %s\nDerivatives selected:\s\n\n" \
+              "output directory provided: %s\nDerivatives selected:%s\n\n" \
               % (pipeline_output_folder, resource_list)
         raise Exception(err)
```

**Comment by sgiavasis** [comment]
Thank you! Noting here your fix is included in the PR linked with #667
