### ISSUE TITLE
subject list creation

### ISSUE THREAD

**Issue by florisvanvugt** [FCP-INDI/C-PAC#671]
Me again - sorry to be spamming this forum.

I am not sure if your definition of the subject list name is correct.
It says 
```
subjectListName | A name for the subject list. | A list containing a string (e.g.,[‘ABIDE’]).
```

But then when I run `cpac_setup.py` with a config file that has:
```
subjectListName : ["pianists"]
```
Then it creates the correct output file (`CPAC_subject_list_pianists.yml`) among other things, but raises an exception:
```
(cpac)floris@colossus:/brains/pianists$ cpac_setup.py data_config.yml 
For any errors or messages check the log file - /brains/pianists/extract_data_logs.log
Extraction Successfully Completed...Input Subjects_list for CPAC - ./CPAC_subject_list.yml
Subject list couldn't be read!
path:  ./CPAC_subject_list_['pianists'].yml
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/bin/cpac_setup.py", line 27, in <module>
    CPAC.utils.extract_data.run(data_config_file)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/extract_data.py", line 753, in run
    generate_supplementary_files(c.outputSubjectListLocation, c.subjectListName)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/extract_data.py", line 408, in generate_supplementary_files
    raise Exception
Exception
```

If however I specify in the data configuration file:
```
subjectListName : pianists
```
Then it  creates a subject list `CPAC_subject_list_p.yml` (note just the first letter of the site name) and throws this error:

```
For any errors or messages check the log file - /brains/pianists/extract_data_logs.log
Extraction Successfully Completed...Input Subjects_list for CPAC - ./CPAC_subject_list.yml
Subject list couldn't be read!
path:  ./CPAC_subject_list_pianists.yml
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/bin/cpac_setup.py", line 27, in <module>
    CPAC.utils.extract_data.run(data_config_file)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/extract_data.py", line 753, in run
    generate_supplementary_files(c.outputSubjectListLocation, c.subjectListName)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/extract_data.py", line 408, in generate_supplementary_files
    raise Exception
Exception
```

Again, I made a fix on my repo (see the pull request). Here it is also for completeness:
```
diff --git a/CPAC/utils/extract_data.py b/CPAC/utils/extract_data.py
index cc46b82..05e9c6a 100644
--- a/CPAC/utils/extract_data.py
+++ b/CPAC/utils/extract_data.py
@@ -207,7 +207,7 @@ def extract_data(c, param_map):
     anat_session_present, anat_session_path, anat_relative = \
         check_for_sessions(anat_relative, anat_relative_len)
 
-    f = open(os.path.join(c.outputSubjectListLocation, "CPAC_subject_list_%s.yml" % c.subjectListName[0]), 'wb')
+    f = open(os.path.join(c.outputSubjectListLocation, "CPAC_subject_list_%s.yml" % c.subjectListName), 'wb')
```

**Comment by florisvanvugt** [comment]
Perhaps it should be mentioned somewhere that when one enters scan names, they should not contain "special characters" such as periods, because CPAC will turn them into workflow names and nipype chokes when workflow names contain periods. 
So for example if you have a subject list like this (below) then you will get into trouble later because of the period in the name of the rest block.

```
-
    subject_id: 'CS_04'
    unique_id: ''
    anat: '/brains/pianists.scales.rsfmri/data.reorg/CS_04/T1.nii.gz'
    rest: 
      CS_04.REST: '/brains/pianists.scales.rsfmri/data.reorg/CS_04/REST.nii.gz'
-
    subject_id: 'AS_11'
    unique_id: ''
    anat: '/brains/pianists.scales.rsfmri/data.reorg/AS_11/T1.nii.gz'
    rest: 
      AS_11.REST: '/brains/pianists.scales.rsfmri/data.reorg/AS_11/REST.nii.gz'
```

**Comment by sgiavasis** [comment]
Hi Floris,

Thanks for bringing this up. The cpac_setup.py script has not been updated to match how participant lists are generated now. We'll clean this up in the upcoming point release.

**Comment by sgiavasis** [comment]
The sample data_config.yml has been updated in the dev branch- tagging this for when the docs are updated for this release to fix the subjectListName description. Thanks again.
