### ISSUE TITLE
cwas workflow crashes at joint mask, the exact same script works for 0.3.9.0 on AWS

### ISSUE THREAD

**Issue by kyleliang919** [FCP-INDI/C-PAC#686]
170809-10:42:45,55 workflow INFO:
	 Workflow cwas settings: ['check', 'execution', 'logging']
170809-10:42:45,60 workflow INFO:
	 Running serially.
170809-10:42:45,61 workflow INFO:
	 Executing node joint_mask in dir: /home/barbeytower3/Desktop/cwas/cwas/cwas/joint_mask
170809-10:42:45,70 workflow ERROR:
	 [u'Node joint_mask failed to run on host barbeytower3.']
170809-10:42:45,71 workflow INFO:
	 Saving crash info to /home/barbeytower3/Desktop/cwas/crash-20170809-104245-barbeytower3-joint_mask-c2ab071c-cbae-4b7b-a8ad-918032dd01ce.pklz
170809-10:42:45,71 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1029, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 146, in _run_interface
    self.imports)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/utils/misc.py", line 102, in create_function_from_source
    raise_from(RuntimeError(msg), e)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/future/utils/__init__.py", line 455, in raise_from
    raise e
RuntimeError: 
Error executing function:
 def joint_mask(subjects_file_list, mask_file):
    """
    Creates a joint mask (intersection) common to all the subjects in a provided list
    and a provided mask

    Parameters
    ----------
    subjects_file_list : list of strings
        A length `N` list of file paths of the nifti files of subjects
    mask_file : string
        Path to a mask file in nifti format

    Returns
    -------
    joint_mask : string
        Path to joint mask file in nifti format

    """
    import nibabel as nb
    import numpy as np
    import os

    from CPAC.utils import safe_shape

    nii = nb.load(mask_file)

    mask = nii.get_data().astype('bool')
    for subject_file in subjects_file_list:
        sdata = nb.load(subject_file).get_data().astype(np.float64).sum(-1)
        if not safe_shape(sdata, mask): raise ValueError('Subject %s with volume shape %s conflicts \
                                                          with mask shape %s' % ( subject_file,
                                                                                  str(sdata.shape),
                                                                                  str(mask.shape) ) )
        mask *= sdata.astype('bool')

    print '... joint subject/roi mask loaded'

    img = nb.Nifti1Image(mask, header=nii.get_header(), affine=nii.get_affine())
    img_file = os.path.join(os.getcwd(), 'joint_mask.nii.gz')
    img.to_filename(img_file)

    return img_file

Functions in connection strings have to be standalone.
They cannot be declared either interactively or inside
another function or inline in the connect string. Any
imports should be done inside the function
Interface Function failed to run. 

170809-10:42:45,76 workflow INFO:
	 ***********************************
170809-10:42:45,76 workflow ERROR:
	 could not run node: cwas.joint_mask
170809-10:42:45,76 workflow INFO:
	 crashfile: /home/barbeytower3/Desktop/cwas/crash-20170809-104245-barbeytower3-joint_mask-c2ab071c-cbae-4b7b-a8ad-918032dd01ce.pklz
170809-10:42:45,76 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "cwas.py", line 55, in <module>
    c.run()
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 61, in run
    report_nodes_not_run(notrun)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 101, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

Here is the crash log:
False False
Traceback (most recent call last):
  File "/usr/bin/nipype_display_crash", line 86, in <module>
    debug, args.directory)
  File "/usr/bin/nipype_display_crash", line 16, in display_crash_files
    from nipype.utils.filemanip import loadcrash
  File "/usr/lib/python2.7/dist-packages/nipype/__init__.py", line 77, in <module>
    from pipeline import Node, MapNode, JoinNode, Workflow
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/__init__.py", line 8, in <module>
    from engine import Node, MapNode, JoinNode, Workflow
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 48, in <module>
    from ..interfaces.base import (traits, InputMultiPath, CommandLine,
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/__init__.py", line 10, in <module>
    from io import DataGrabber, DataSink, SelectFiles
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/io.py", line 45, in <module>
    from nipype.interfaces.base import (TraitedSpec, traits, File, Directory,
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 25, in <module>
    from dateutil.parser import parse as parseutc
ImportError: No module named dateutil.parser

**Comment by sgiavasis** [comment]
Hello,

What version of Nipype are you using? This can be checked easily by going into Python and entering:

`import nipype`
`nipype.__version__`

(Those are two _'s on each side).

**Comment by sgiavasis** [comment]
Hi @kyleliang919,

Was there ever any resolution to this? Let us know if this is still an issue and we can help you out.

Best,
Steve

**Comment by kyleliang919** [comment]
There was a resolution by downgrading c-pac to the previous version and I fixed the problem by doing that. I did not follow up the issue. Sorry.

**Comment by sgiavasis** [comment]
No worries, wanted to ensure everything was going smoothly.

We are currently on C-PAC v1.1.0, so if you upgrade at some point, let us know if you have any questions or concerns.
