### ISSUE TITLE
TypeError from participant list while testing configuration

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#701]
Get this when there are "scan_parameters: null" in the participant list, and you use that participant list while running the "Test Configuration" option in the pipeline config builder:

> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/windows/config_window.py", line 576, in testConfig
> 
>     sub_flg = self.test_sublist(sublist)
> 
>   File "/usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/windows/config_window.py", line 460, in test_sublist
> 
>     if '.nii' not in func_file:
> 
> TypeError: argument of type 'NoneType' is not iterable

**Comment by shnizzedy** [comment]
Deprecated by #1262
