### ISSUE TITLE
Urgent: Issue running basc module

### ISSUE THREAD

**Issue by dpisner453** [FCP-INDI/C-PAC#708]
When I run individual_stability_matrices with CPAC's basc workflow, the workflow consistently crashes (this occurs with and without the MultiProc plugin):
```
from CPAC import basc
from itertools import repeat

input_files = ['/PATH/TO/SUBJECT/FUNCFILE/002/002.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/005/005.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/007/007.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/008/008.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/009/009.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/012/012.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/014/014.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/020/020.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/025/025.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/026/026.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/028/028.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/033/033.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/034/034.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/036/036.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/037/037.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/039/039.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/042/042.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/046/046.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/047/047.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/048/048.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/050/050.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/051/051.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/052/052.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/053/053.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/054/054.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/055/055.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/056/056.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/059/059.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/060/060.nii.gz','/PATH/TO/SUBJECT/FUNCFILE/061/061.nii.gz']

l = [0.8]
affins = [x for item in l for x in repeat(item, 30)]

b = basc.create_basc()
b.base_dir = '/PATH/TO/WORKING_DIR/basc'
b.inputs.inputspec.roi = '/PATH/TO/WORKING_DIR/ROI_mask.nii.gz'
b.inputs.inputspec.subjects = input_files
b.inputs.inputspec.k_clusters = 100
b.inputs.inputspec.dataset_bootstraps = 10
b.inputs.inputspec.timeseries_bootstraps = 10
b.inputs.inputspec.affinity_threshold = affins
b.run(plugin='MultiProc', plugin_args={'n_procs': 10})

```
	 Currently running 10 tasks, and 19 jobs ready. Free memory (GB): 82.72/84.72, Free processors: 0/10
171205-01:29:21,750 workflow ERROR:
	 Node _individual_stability_matrices3 failed to run on host c455-044.stampede2.tacc.utexas.edu.
171205-01:29:21,753 workflow ERROR:
	 Saving crash info to /work/04171/dpisner/data/ABM/network_analysis/crash-20171205-012921-dpisner-_individual_stability_matrices3-02198976-6469-40dc-ada0-35bd0db1d1fe.pklz
Traceback (most recent call last):
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1089, in run
    runtime = self._run_interface(runtime)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 137, in _run_interface
    out = function_handle(**args)
  File "<string>", line 45, in nifti_individual_stability
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/CPAC/basc/utils.py", line 274, in individual_stability_matrix
    S += adjacency_matrix(cluster_timeseries(Y_b.T, k_clusters, similarity_metric = 'correlation', affinity_threshold = affinity_threshold)[:,np.newaxis])
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/CPAC/basc/utils.py", line 142, in cluster_timeseries
    eigen_discrete = discretisation(eigen_vec)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/CPAC/basc/python_ncut_lib.py", line 196, in discretisation
    U, S, Vh = svd(tSVD)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/scipy/_lib/_util.py", line 238, in _asarray_validated
    a = toarray(a)
  File "/home1/04171/dpisner/.local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1022, in asarray_chkfinite
#     **"array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs**

What is going on here and what can I do to fix it?

**Comment by sgiavasis** [comment]
Hello @dpisner453 ,

The BASC workflow in the CPAC repo does not reflect the most recent developments of BASC (we removed BASC from CPAC's user guide and GUI for now). It is currently being developed further by @akinikolaidis, and will eventually be integrated back into CPAC once it is complete.

The most recent codebase for the BASC project, however, can be found on his repo:
https://github.com/AkiNikolaidis/PyBASC

Note, we are not currently actively supporting the code in that repo for a user base at this time, as it is still in development.

Best,
Steve

**Comment by dpisner453** [comment]
Hi Steve, 
Already working with Aki on this, was just curious as to whether the CPAC implementation was working, and it appears that it is not. Feel free to close this issue!

Thanks,
Derek

**Comment by sgiavasis** [comment]
Sounds good, thanks!

I'd like to remove any vagueness about whether or not the CPAC implementation is working to avoid misleading anyone- what was the entry point for you? For example, is it because of the code that is sitting in the repository?

Thanks-
Steve
