### ISSUE TITLE
Error when executing benchmark

### ISSUE THREAD

**Issue by tragus1** [FCP-INDI/C-PAC#722]
I experience the following error when executing the benchmark, do you have any idea how to solve this problem?

Thank you,
Boris

cpac_run.py ~/Desktop/benchmark_package/settings/configs/pipeline_config_benchmark.yml ~/Desktop/benchmark_package/settings/subject_lists/CPAC_benchmark_participants.yml
Traceback (most recent call last):
  File "/usr/local/bin/cpac_run.py", line 52, in <module>
    CPAC.pipeline.cpac_runner.run(config_file, subject_list_file)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_runner.py", line 426, in run
    strategies = sorted(build_strategies(c))
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_runner.py", line 122, in build_strategies
    config_iterables = {'_threshold': eval('configuration.spikeThreshold'), '_compcor': eval('configuration.Regressors'), '_target_angle_deg': eval('configuration.targetAngleDeg')}
  File "<string>", line 1, in <module>
AttributeError: 'Configuration' object has no attribute 'spikeThreshold'

**Comment by sgiavasis** [comment]
Hello Boris,

The spikeThreshold config key is a new updated name for the scrubbing & de-spiking threshold. The pipeline config file in the benchmark package has not been revised to match this (sorry for the inconvenience)- a complete runnable version will be available in the next release, 1.0.3.

In the meantime, to get you running, the most up to date version of the pipeline config is available here:
https://github.com/FCP-INDI/C-PAC/blob/master/configs/pipeline_config.yml

Please let us know if you need any more assistance.

Best,
Steve

**Comment by tragus1** [comment]
Thank you for your quick reply. Sorry for bothering you again but with the new pipline_config.yml I get the following error: 
cpac_run.py ~/Desktop/benchmark_package/settings/configs/pipeline_config.yml ~/Desktop/benchmark_package/settings/subject_lists/CPAC_benchmark_participants.yml
[sudo] password for boris:
Traceback (most recent call last):
  File "/usr/local/bin/cpac_run.py", line 52, in <module>
    CPAC.pipeline.cpac_runner.run(config_file, subject_list_file)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_runner.py", line 426, in run
    strategies = sorted(build_strategies(c))
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_runner.py", line 122, in build_strategies
    config_iterables = {'_threshold': eval('configuration.spikeThreshold'), '_compcor': eval('configuration.Regressors'), '_target_angle_deg': eval('configuration.targetAngleDeg')}
  File "<string>", line 1, in <module>
AttributeError: 'Configuration' object has no attribute 'Regressors'

**Comment by sgiavasis** [comment]
Hi @tragus1,

Sorry we haven't gotten back to this- are you still having issues? Let us know and we can help.

Best,
Steve
