### ISSUE TITLE
Error building a subject list

### ISSUE THREAD

**Issue by tragus1** [FCP-INDI/C-PAC#726]
Hi,

when I´m building a subject list I get the following error

sudo cpac_setup.py ~/Desktop/test_pip_smc/settings/subjects/data_config.yml
For any errors or messages check the log file - /home/boris/Desktop/extract_data_logs.log
Traceback (most recent call last):
  File "/usr/local/bin/cpac_setup.py", line 25, in <module>
    CPAC.utils.extract_data.run(data_config_file)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/utils/extract_data.py", line 663, in run
    CPAC.utils.build_sublist.build_sublist(data_config)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/utils/build_sublist.py", line 991, in build_sublist
    s3_str in anat_template.lower() and s3_str not in func_template.lower()) or \
AttributeError: 'list' object has no attribute 'lower'

in the Log file I have the following:

DEBUG 2017-12-16 17:25:38,439 658 no scan parameters csv included
make sure you turn off slice timing correction option
in CPAC configuration

Do you have any idea whats wrong here?
The scanParametersCSV ist set to None...

This ist my data_config.yml file:

# Select if data is organized using BIDS standard or custom format
dataFormat: ['Custom']

# dataFormat: ['BIDS']
# If using BIDS, base directory of BIDS-organized data
# (can use an S3 bucket path as well
# bidsBaseDir:  s3://bucket_name/directory_to_data
bidsBaseDir: None

# File Path Template for Anatomical Files. Place tags for the appropriate data
# directory levels with tags such as {site}, {participant}, {session}, and
# {series}. These are not all required. See User Guide for more detailed
# instructions. Use this if data is not in BIDS format.
anatomicalTemplate: ['~/Desktop/test_pip_smc/in/{site}/{participant}/anat']

# File Path Template for Functional Files. Place tags for the appropriate data
# directory levels with tags such as {site}, {participant}, {session}, and
# {series}. These are not all required. See User Guide for more detailed
# instructions. Use this if data is not in BIDS format.
functionalTemplate: ['~/Desktop/test_pip_smc/in/{site}/{participant}/fcMRI']

# Include only a sub-set of the subjects present in the folders defined above.
# List subjects in this list (e.g., sub101, sub102) or provide the path to a
# text file with one subject on each line. If 'None' is specified, CPAC will
# include all subjects.
# subjectList: ['sub01', 'sub02']
# subjectList: /path/to/text_file.txt
subjectList: None

# Exclude a sub-set of the subjects present in the folders defined above.
# List subjects in this box (e.g., sub101, sub102) or provide the path to a
# text file with one subject on each line. If 'None' is specified, CPAC will
# not exclude any subjects.
# exclusionSubjectList: ['sub01', 'sub02']
# exclusionSubjectList: /path/to/text_file.txt
exclusionSubjectList: None

# Include only a sub-set of the sites present in the folders defined above.
# List sites in this box (e.g., NYU, UCLA) or provide the path to a text file
# with one site on each line. If 'None' is specified, CPAC will include all
# sites.
# siteList: ['site01', 'site02']
siteList: None

# Required for Slice Timing Correction. Path to a .csv file containing
# information about scan acquisition parameters. For instructions on how to
# create this file, see the User Guide. If 'None' is specified, CPAC will skip
# Slice Timing Correction.
scanParametersCSV: None

# Required if downloading data from a non-public S3 bucket on Amazon Web
# Services instead of using local files. Enter a filepath to a creds CSV file.
awsCredentialsFile: None

# Directory where CPAC should place subject list files.
outputSubjectListLocation: test_pip_smc/settings/subjects

# A label to be appended to the generated subject list files.
subjectListName: [‘SMC’]

**Comment by sgiavasis** [comment]
Hi @tragus1,

Sorry this hasn't been addressed- are you still having issues regarding this? Let us know and we can help.

Best,
Steve

**Comment by sgiavasis** [comment]
Closing due to inactivity.
