### ISSUE TITLE
Error name: cpac_runner_0001 SubjectList

### ISSUE THREAD

**Issue by jdkent** [FCP-INDI/C-PAC#751]
### Setup:
[C-PAC (docker)](https://github.com/jdkent/CPAC/tree/upgrade_dockerfile)

### Command
```
import CPAC
from nipype.pipeline.plugins.callback_log import log_nodes_cb

config_file = 'cpac_pipeline_config_template.yml'
data_config_file = 'cpac_data_config_test.yml'

plugin_args = {'n_procs': int(pipeline_config['maxCoresPerParticipant']),
                   'memory_gb': int(pipeline_config['maximumMemoryPerParticipant']),
                   'callback_log': log_nodes_cb}

print("Starting participant level processing")
CPAC.pipeline.cpac_runner.run(config_file, data_config_file,
                                  plugin='MultiProc', plugin_args=plugin_args)
```
### ERROR
```
ERROR: Subject list file not in proper format - check if you loaded the correct file?
Error name: cpac_runner_0001


Traceback (most recent call last):
  File "./run.py", line 321, in <module>
    plugin='MultiProc', plugin_args=plugin_args)
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/pipeline/cpac_runner.py", line 448, in run
    raise Exception
Exception
```

### cpac_data_config_test.yml
```
# Select if data is organized using BIDS standard or custom format
# dataFormat: ['Custom']
dataFormat: ['BIDS']

# If using BIDS, base directory of BIDS-organized data
# (can use an S3 bucket path as well
# bidsBaseDir:  s3://bucket_name/directory_to_data
bidsBaseDir: /mnt/Projects/PACR-AD/Imaging/BIDS/

# File Path Template for Anatomical Files. Place tags for the appropriate data
# directory levels with tags such as {site}, {participant}, {session}, and
# {series}. These are not all required. See User Guide for more detailed
# instructions. Use this if data is not in BIDS format.
anatomicalTemplate: None

# File Path Template for Functional Files. Place tags for the appropriate data
# directory levels with tags such as {site}, {participant}, {session}, and
# {series}. These are not all required. See User Guide for more detailed
# instructions. Use this if data is not in BIDS format.
functionalTemplate: None

# Include only a sub-set of the subjects present in the folders defined above.
# List subjects in this list (e.g., sub101, sub102) or provide the path to a
# text file with one subject on each line. If 'None' is specified, CPAC will
# include all subjects.
# subjectList: ['sub01', 'sub02']
# subjectList: /path/to/text_file.txt
subjectList: None

# Exclude a sub-set of the subjects present in the folders defined above.
# List subjects in this box (e.g., sub101, sub102) or provide the path to a
# text file with one subject on each line. If 'None' is specified, CPAC will
# not exclude any subjects.
# exclusionSubjectList: ['sub01', 'sub02']
# exclusionSubjectList: /path/to/text_file.txt
exclusionSubjectList: None

# Include only a sub-set of the sites present in the folders defined above.
# List sites in this box (e.g., NYU, UCLA) or provide the path to a text file
# with one site on each line. If 'None' is specified, CPAC will include all
# sites.
# siteList: ['site01', 'site02']
siteList: None

# Required for Slice Timing Correction. Path to a .csv file containing
# information about scan acquisition parameters. For instructions on how to
# create this file, see the User Guide. If 'None' is specified, CPAC will skip
# Slice Timing Correction.
scanParametersCSV: None

# Required if downloading data from a non-public S3 bucket on Amazon Web
# Services instead of using local files. Enter a filepath to a creds CSV file.
# awsCredentialsFile: None

# Directory where CPAC should place subject list files.
outputSubjectListLocation: /mnt/Projects/PACR-AD/Imaging/BIDS/derivatives/cpac/

# A label to be appended to the generated subject list files.
subjectListName: ['PACR']
```
### EXAMPLE SUBJECT ORGANIZATION
```
.
|-- ses-post
|   |-- anat
|   |   |-- sub-controlGE154_ses-post_T1w.nii.gz
|   |   |-- sub-controlGE154_ses-post_acq-1_T2w.nii.gz
|   |   `-- sub-controlGE154_ses-post_acq-2_T2w.nii.gz
|   |-- cbf
|   |   |-- sub-controlGE154_ses-post_acq-ASL_cbf.nii.gz
|   |   `-- sub-controlGE154_ses-post_acq-cbf_cbf.nii.gz
|   |-- dwi
|   |   |-- sub-controlGE154_ses-post_acq-60D_dwi.bval
|   |   |-- sub-controlGE154_ses-post_acq-60D_dwi.bvec
|   |   |-- sub-controlGE154_ses-post_acq-60D_dwi.nii.gz
|   |   |-- sub-controlGE154_ses-post_acq-B0_dwi.bval
|   |   |-- sub-controlGE154_ses-post_acq-B0_dwi.bvec
|   |   `-- sub-controlGE154_ses-post_acq-B0_dwi.nii.gz
|   |-- fmap
|   |   |-- sub-controlGE154_ses-post_fieldmap.json
|   |   |-- sub-controlGE154_ses-post_fieldmap.nii.gz
|   |   `-- sub-controlGE154_ses-post_magnitude.nii.gz
|   `-- func
|       |-- sub-controlGE154_ses-post_task-flanker_bold.nii.gz
|       |-- sub-controlGE154_ses-post_task-flanker_events.tsv
|       `-- sub-controlGE154_ses-post_task-rest_bold.nii.gz
`-- ses-pre
    |-- anat
    |   |-- sub-controlGE154_ses-pre_T1w.nii.gz
    |   |-- sub-controlGE154_ses-pre_acq-1_T2w.nii.gz
    |   `-- sub-controlGE154_ses-pre_acq-2_T2w.nii.gz
    |-- cbf
    |   |-- sub-controlGE154_ses-pre_acq-ASL_cbf.nii.gz
    |   `-- sub-controlGE154_ses-pre_acq-cbf_cbf.nii.gz
    |-- dwi
    |   |-- sub-controlGE154_ses-pre_acq-60D_dwi.bval
    |   |-- sub-controlGE154_ses-pre_acq-60D_dwi.bvec
    |   |-- sub-controlGE154_ses-pre_acq-60D_dwi.nii.gz
    |   |-- sub-controlGE154_ses-pre_acq-B0_dwi.bval
    |   |-- sub-controlGE154_ses-pre_acq-B0_dwi.bvec
    |   `-- sub-controlGE154_ses-pre_acq-B0_dwi.nii.gz
    |-- fmap
    |   |-- sub-controlGE154_ses-pre_fieldmap.json
    |   |-- sub-controlGE154_ses-pre_fieldmap.nii.gz
    |   `-- sub-controlGE154_ses-pre_magnitude.nii.gz
    `-- func
        |-- sub-controlGE154_ses-pre_task-flanker_bold.nii.gz
        |-- sub-controlGE154_ses-pre_task-flanker_events.tsv
        `-- sub-controlGE154_ses-pre_task-rest_bold.nii.gz
```
### Question:
Does this yml look correct? Did I set up the files wrong?

Thank you for this program, it looks like it will be very useful.

**Comment by sgiavasis** [comment]
Hi @jdkent ,

The YAML file you posted is the file CPAC's participant list builder uses to generate the participant list (but it isn't the list itself). You can load this file into the builder in the GUI and create the list, then try using that.

By the way, we recently released a new version of CPAC, and the participant list builder has changed significantly. The BIDS-app Docker image will be updated to reflect this new version soon. Note, we started calling the participant list the "data configuration" to be consistent with the BIDS-app. More details on how to use the new data config builder are available here:
http://fcp-indi.github.io/docs/user/subject_list_config.html

Please let me know if you have any questions!

Best,
Steve

**Comment by jdkent** [comment]
Thanks Steve, I must have missed this response! I've been going down other analysis pipelines currently, but the lab will circle back to C-PAC.
