### ISSUE TITLE
3dROIstats not in the expected format. get_roi_num_list and 3dTCorr1D crashing.

### ISSUE THREAD

**Issue by rgykim** [FCP-INDI/C-PAC#771]
Hello, I am running individual analysis on the latest build of CPAC, but I am getting multiple instances of crash logs for the functions: `get_roi_num_list` and `3dTCorr1D`. It seems that these crashes occur due to the unexpected format of 3dROIstats. Is this an issue with AFNI (version 17.3.00) or my CPAC pipeline? 

I have attached the contents of the 3dROIstats directory: [3dROIstats.zip](https://github.com/FCP-INDI/C-PAC/files/1775925/3dROIstats.zip)

Below are the crash logs for this process.

### `get_roi_num_list` crash log:
```shell
File: crash-20180301-225420-kim-get_roi_num_list.a0.b1.c0.a0.a08-f418aa64-ed66-4892-b065-49413c8bdec8.pklz
Node: resting_preproc_C0001-1211_ses-1.sca_roi_0.get_roi_num_list.a0.b1.c0.a0.a08
Working directory: /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/sca_roi_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/get_roi_num_list


Node inputs:

function_str = def get_roi_num_list(timeseries_file, prefix=None):
    # extracts the ROI labels from the 3dROIstats output CSV file
    with open(timeseries_file, "r") as f:
        roi_file_lines = f.read().splitlines()

    roi_err = "\n\n[!] The output of 3dROIstats, used in extracting the " \
              "timeseries, was not in the expected format.\n\nROI output " \
              "file: %s\n\n" % timeseries_file

    for line in roi_file_lines:
        if "Mean_" in line:
            try:
                roi_list = line.split("\t")
                # clear out any blank strings/non ROI labels in the list
                roi_list = [x for x in roi_list if "Mean" in x]
                # rename labels
                roi_list = [x.replace("Mean", "ROI").replace(" ", "") \
                            for x in roi_list]
            except:
                raise Exception(roi_err)
            break
    else:
        raise Exception(roi_err)

    if prefix:
        temp_rois = []
        for roi in roi_list:
            roi = prefix + "_" + str(roi)
            temp_rois.append(roi)
        roi_list = temp_rois

    return roi_list

ignore_exception = False
prefix = sca
timeseries_file = /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/roi_timeseries_for_sca_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dROIstats/roi_stats.csv



Traceback: 
Traceback (most recent call last):
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 496, in _run_interface
    raise out
Exception: 

[!] The output of 3dROIstats, used in extracting the timeseries, was not in the expected format.

ROI output file: /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/roi_timeseries_for_sca_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dROIstats/roi_stats.csv


Interface Function failed to run. 
```
### `3dTCorr1D` crash log:
```shell
File: crash-20180301-225420-kim-3dTCorr1D.a0.b1.c0.a0.a08-65c56574-093f-4501-93b4-575fda350421.pklz
Node: resting_preproc_C0001-1211_ses-1.sca_roi_0.3dTCorr1D.a0.b1.c0.a0.a08
Working directory: /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/sca_roi_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dTCorr1D


Node inputs:

args = <undefined>
environ = {}
ignore_exception = False
ktaub = <undefined>
out_file = <undefined>
outputtype = NIFTI_GZ
pearson = True
quadrant = <undefined>
spearman = <undefined>
terminal_output = stream
xset = /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/sca_roi_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dTCorr1D/scrubbed_preprocessed.nii.gz
y_1d = /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/roi_timeseries_for_sca_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dROIstats/roi_stats.csv



Traceback: 
Traceback (most recent call last):
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1663, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/afni/base.py", line 128, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1697, in _run_interface
    self.raise_exception(runtime)
  File "/home/kim/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1621, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
3dTcorr1D  -pearson -prefix scrubbed_preprocessed_correlation.nii.gz  /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/sca_roi_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dTCorr1D/scrubbed_preprocessed.nii.gz  /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/roi_timeseries_for_sca_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dROIstats/roi_stats.csv
Standard output:

Standard error:
++ 3dTcorr1D: AFNI version=AFNI_17.3.00 (Oct 12 2017) [64-bit]
 + reading dataset file /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/sca_roi_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dTCorr1D/scrubbed_preprocessed.nii.gz
 + reading 1D file /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/roi_timeseries_for_sca_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dROIstats/roi_stats.csv
** FATAL ERROR: Can't read 1D file /data/ohsu/hipp_rsfmri/HCP/cpac/2018_pipeline/temp/resting_preproc_C0001-1211_ses-1/roi_timeseries_for_sca_0/_scan_func-1/_threshold_0.5/_compcor_ncomponents_5_selector_pc10.linear1.wm1.global0.motion1.quadratic1.gm1.compcor0.csf1/_bandpass_freqs_0.01.0.1/_mask_hc_rh_6_sphere/3dROIstats/roi_stats.csv
** Program compile date = Oct 12 2017
Return code: 1
Interface TCorr1D failed to run.
```

**Comment by sgiavasis** [comment]
Continued in the forum post:
https://groups.google.com/forum/#!topic/cpax_forum/g8NqbqUMJmM
