### ISSUE TITLE
User not getting all outputs during cluster run

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#796]
C-PAC version 0.3.9

File: crash/crash-20180525-104143-florid01-frequency_filter_0.aI.a0.b1.c0.c0.c0.c0.pklz
Node: resting_preproc_50608_session_1.frequency_filter_0.aI.a0.b1.c0.c0.c0.c0
Working directory: /ifs/data/li_subtypes/ABIDE_I/work/resting_preproc_50608_session_1/_scan_rest_1_rest/_csf_threshold_0.96/_gm_threshold_0.7/_wm_threshold_0.96/_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic1.gm0.compcor1.csf0/_bandpass_freqs_0.01.0.1/frequency_filter_0

Node inputs:

bandpass_freqs = [0.01, 0.1]
function_str = S'def bandpass_voxels(realigned_file, bandpass_freqs, sample_period = None):\n    """\n    Performs ideal bandpass filtering on each voxel time-series.\n\n    Parameters\n    ----------\n    realigned_file : string\n        Path of a realigned nifti file.\n    bandpass_freqs : tuple\n        Tuple containing the bandpass frequencies. (LowCutoff, HighCutoff)\n    sample_period : float, optional\n        Length of sampling period in seconds.  If not specified,\n        this value is read from the nifti file provided.\n\n    Returns\n    -------\n    bandpassed_file : string\n        Path of filtered output (nifti file).\n\n    """\n\n    import os\n    import nibabel as nb\n    import numpy as np\n\n    def ideal_bandpass(data, sample_period, bandpass_freqs):\n        #Derived from YAN Chao-Gan 120504 based on REST.\n        from scipy.fftpack import fft, ifft\n\n    #    sample_period = T\n    #    LowCutoff = 10.\n    #    HighCutoff = 15.\n    #    data = x\n\n        def nextpow2(n):\n            x = np.log2(n)\n            return 2**np.ceil(x)\n\n        sample_freq = 1./sample_period\n        sample_length = data.shape[0]\n\n        data_p = np.zeros(nextpow2(sample_length))\n        data_p[:sample_length] = data\n\n        LowCutoff, HighCutoff = bandpass_freqs\n\n        if(LowCutoff is None): #No lower cutoff (low-pass filter)\n            low_cutoff_i = 0\n        elif(LowCutoff > sample_freq/2.): #Cutoff beyond fs/2 (all-stop filter)\n            low_cutoff_i = int(data_p.shape[0]/2)\n        else:\n            low_cutoff_i = np.ceil(LowCutoff*data_p.shape[0]*sample_period).astype(\'int\')\n\n        if(HighCutoff > sample_freq/2. or HighCutoff is None): #Cutoff beyond fs/2 or unspecified (become a highpass filter)\n            high_cutoff_i = int(data_p.shape[0]/2)\n        else:\n            high_cutoff_i = np.fix(HighCutoff*data_p.shape[0]*sample_period).astype(\'int\')\n\n        freq_mask = np.zeros_like(data_p, dtype=\'bool\')\n        freq_mask[low_cutoff_i:high_cutoff_i+1] = True\n        freq_mask[data_p.shape[0]-high_cutoff_i:data_p.shape[0]+1-low_cutoff_i] = True\n\n\n        f_data = fft(data_p)\n        f_data[freq_mask != True] = 0.\n        data_bp = np.real_if_close(ifft(f_data)[:sample_length])\n\n        return data_bp\n\n    nii = nb.load(realigned_file)\n    data = nii.get_data().astype(\'float64\')\n    mask = (data != 0).sum(-1) != 0\n    Y = data[mask].T\n    Yc = Y - np.tile(Y.mean(0), (Y.shape[0], 1))\n\n    if not sample_period:\n        hdr = nii.get_header()\n        sample_period = float(hdr.get_zooms()[3])\n        # Sketchy check to convert TRs in millisecond units\n        if sample_period > 20.0:\n            sample_period /= 1000.0\n\n    print \'Frequency filtering using sample period: \', sample_period, \'sec\'\n\n    Y_bp = np.zeros_like(Y)\n    for j in range(Y.shape[1]):\n        Y_bp[:,j] = ideal_bandpass(Yc[:,j], sample_period, bandpass_freqs)\n\n    data[mask] = Y_bp.T\n    img = nb.Nifti1Image(data, header=nii.get_header(), affine=nii.get_affine())\n    bandpassed_file = os.path.join(os.getcwd(), \'bandpassed_demeaned_filtered.nii.gz\')\n    img.to_filename(bandpassed_file)\n\n    return bandpassed_file\n'
.
ignore_exception = False
realigned_file = /ifs/data/li_subtypes/ABIDE_I/work/resting_preproc_50608_session_1/nuisance_0/_scan_rest_1_rest/_csf_threshold_0.96/_gm_threshold_0.7/_wm_threshold_0.96/_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic1.gm0.compcor1.csf0/residuals/residual.nii.gz
sample_period = <undefined>

Traceback: 
Traceback (most recent call last):
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 87, in bandpass_voxels
  File "<string>", line 42, in ideal_bandpass
TypeError: 'numpy.float64' object cannot be interpreted as an index
Interface Function failed to run.

**Comment by sgiavasis** [comment]
This was resolved in:
https://github.com/FCP-INDI/C-PAC/issues/665

Also referenced:
https://github.com/FCP-INDI/C-PAC/issues/651

Advising user to either upgrade C-PAC install, or to temporarily lock the Numpy install to version 1.11.

**Comment by sgiavasis** [comment]
User is now running smoothly.
