### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'info'

### ISSUE THREAD

**Issue by Salonijain27** [FCP-INDI/C-PAC#828]
I get 
```
AttributeError: 'NoneType' object has no attribute 'info' 
```
 error when i run the cpac_run.py command in a Linux terminal. I have retraced my steps below:
I create a data configuration file which looks like :
```
- anat: /home/saloni/NYU/0025025/session_1/anat_1/anat.nii.gz
  func:
    func-1:
      scan: /home/saloni/NYU/0025025/session_1/rest_1/rest.nii.gz
  site: NYU
  subject_id: '0025025'
  unique_id: session_1
- anat: /home/saloni/NYU/0025025/session_2/anat_1/anat.nii.gz
  func:
    func-1:
      scan: /home/saloni/NYU/0025025/session_2/rest_1/rest.nii.gz
  site: NYU
  subject_id: '0025025'
  unique_id: session_2
```
After which I create a pipeline using the CPAC GUI to pre-process the fmri images. Then I run the cpac_run.py /path/to/cpac_pipeline.yml /path/to/data_config.yml and get the following error
```
Process Process-1:
Traceback (most recent call last):
  File "/path/to/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/path/to/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/.local/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 278, in prep_workflow
    logger.info(cores_msg)
AttributeError: 'NoneType' object has no attribute 'info'
found dead job  <Process(Process-1, stopped[1])>
```
I am using the latest version of CPAC and have installed all the dependencies as per the instruction in:
[http://fcp-indi.github.io/docs/user/install.html](url)

**Comment by Salonijain27** [comment]
Hi Nanditha,
Thank you so much :D . I had nipype=0.13.1 as well as nipype=1.0.0 installed and it was using nipype=1.0.0 . I changed it to nipype=0.13.1 and that solved the above error. 

Thank you!
Saloni Jain
