### ISSUE TITLE
ERROR: Invalid Connection: ROI Timeseries analysis

### ISSUE THREAD

**Issue by Salonijain27** [FCP-INDI/C-PAC#829]
I create a data configuration file and a pipeline for pre-processing fMRI images. When I run the cpac_run.py command I get the following error:
```
180822-19:18:17,701 workflow INFO:
ERROR: Invalid Connection: ROI Timeseries analysis: 0, resource_pool: {'anatomical_gm_mask': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.gm_mask'), 'functional_to_anat_linear_xfm': (resting_preproc_0025025_session_1.func_to_anat_bbreg_0, 'outputspec.func_to_anat_linear_xfm'), 'anatomical_wm_mask': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.wm_mask'), 'anatomical_brain': (resting_preproc_0025025_session_1.anat_preproc_0, 'outputspec.brain'), 'seg_partial_volume_files': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.partial_volume_files'), 'movement_parameters': (resting_preproc_0025025_session_1.fristons_parameter_model_0, 'outputspec.movement_file'), 'seg_partial_volume_map': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.partial_volume_map'), 'max_displacement': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.max_displacement'), 'seg_mixeltype': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.mixeltype'), 'mni_to_anatomical_nonlinear_xfm': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.inverse_warp_field'), 'ants_initial_xfm': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.ants_initial_xfm'), 'mean_functional': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.example_func'), 'functional_preprocessed_mask': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.preprocessed_mask'), 'raw_functional': (resting_preproc_0025025_session_1.func_gather_0, 'outputspec.rest'), 'seg_probability_maps': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.probability_maps'), 'functional_preprocessed': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.preprocessed'), 'frame_wise_displacement_jenkinson': (resting_preproc_0025025_session_1.gen_motion_stats_0, 'outputspec.FDJ_1D'), 'functional_freq_filtered': (resting_preproc_0025025_session_1.frequency_filter_0, 'bandpassed_file'), 'ants_rigid_xfm': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.ants_rigid_xfm'), 'anatomical_csf_mask': (resting_preproc_0025025_session_1.seg_preproc_0, 'outputspec.csf_mask'), 'anat_to_mni_ants_composite_xfm': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.composite_transform'), 'anatomical_to_standard': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.normalized_output_brain'), 'mean_functional_in_anat': (resting_preproc_0025025_session_1.func_to_anat_bbreg_0, 'outputspec.anat_func'), 'anatomical_to_mni_nonlinear_xfm': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.warp_field'), 'motion_correct': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.motion_correct'), 'ants_affine_xfm': (resting_preproc_0025025_session_1.anat_mni_ants_register_0, 'outputspec.ants_affine_xfm'), 'coordinate_transformation': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.oned_matrix_save'), 'functional_brain_mask': (resting_preproc_0025025_session_1.func_preproc_automask_0, 'outputspec.mask'), 'frame_wise_displacement_power': (resting_preproc_0025025_session_1.gen_motion_stats_0, 'outputspec.FDP_1D'), 'slice_time_corrected': (resting_preproc_0025025_session_1.func_slice_timing_correction_0, 'out_file'), 'motion_params': (resting_preproc_0025025_session_1.gen_motion_stats_0, 'outputspec.motion_params'), 'anatomical_reorient': (resting_preproc_0025025_session_1.anat_preproc_0, 'outputspec.reorient'), 'power_params': (resting_preproc_0025025_session_1.gen_motion_stats_0, 'outputspec.power_params')}

Error name: cpac_pipeline_0031

This is a pipeline creation error - the workflows have not started yet.

Process Process-1:
Traceback (most recent call last):
  File "/path/to/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/path/to/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/.local/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 3392, in prep_workflow
    'functional_to_standard')
  File "/path/to/.local/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 111, in get_node_from_resource_pool
    return self.resource_pool[resource_key]
KeyError: 'functional_to_standard'
found dead job  <Process(Process-1, stopped[1])>
```
I have attached my pipeline.yml file in form of a text file for reference.
[pipeline.txt](https://github.com/FCP-INDI/C-PAC/files/2315522/pipeline.txt)

**Comment by anibalsolon** [comment]
Hi @Salonijain27 could you please inform us what was the problem?
So we can improve the way that it is showed to the user.

Anyway, thanks for reaching out!

**Comment by Salonijain27** [comment]
Hi @anibalsolon a couple of the pipeline settings did not go with each other. Once I changed my pipeline settings this error was resolved.
However, I am getting a new error :
```
180827-18:22:07,774 workflow ERROR:
	 [u'Node GM_mask failed to run on host name-ubuntu.']
180827-18:22:07,775 workflow INFO:
	 Saving crash info to path/to/NYU/crash_log/crash-20180827-182207-saloni-GM_mask-3c97edd4-53de-4f57-b181-5cbede89732d.pklz
180827-18:22:07,775 workflow INFO:
	 Traceback (most recent call last):
  File "/path/to/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "path/to/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in run
    self._get_inputs()
  File "path/to/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 467, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 223, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/path/to/.local/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 83, in validate
    validated_value = super(BaseFile, self).validate(object, name, value)
  File "/path/to/.local/lib/python2.7/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/path/to/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'in_file' trait of a MultiImageMathsInput instance must be an existing file name, but a value of None <type 'NoneType'> was specified.
Error setting node input:
Node: GM_mask
input: in_file
results_file: /tmp/resting_preproc_0025029_session_2/seg_preproc_0/segment/result_segment.pklz
value: None

```
