### ISSUE TITLE
Error setting node input

### ISSUE THREAD

**Issue by Salonijain27** [FCP-INDI/C-PAC#830]
While executing the cpac_run.py command to pre-process the fmri images I get the following errors:
```
180827-18:37:09,442 workflow INFO:
	 Collecting precomputed outputs
180827-18:37:09,449 workflow ERROR:
	 [u'Node CSF_mask failed to run on host saloni-ubuntu.']
180827-18:37:09,479 workflow INFO:
	 Saving crash info to /home/saloni/NYU/crash_log/crash-20180827-183709-saloni-CSF_mask-01e839e2-3930-4e76-8a6b-1e69f5a36a5c.pklz
180827-18:37:09,480 workflow INFO:
	 Traceback (most recent call last):
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in run
    self._get_inputs()
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 467, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 223, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 83, in validate
    validated_value = super(BaseFile, self).validate(object, name, value)
  File "/home/saloni/.local/lib/python2.7/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/home/saloni/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'in_file' trait of a MultiImageMathsInput instance must be an existing file name, but a value of None <type 'NoneType'> was specified.
Error setting node input:
Node: CSF_mask
input: in_file
results_file: /tmp/resting_preproc_0025025_session_1/seg_preproc_0/segment/result_segment.pklz
value: None
```
I have attached my pipeline.yml file in the form of a text file below.
[pipeline.txt](https://github.com/FCP-INDI/C-PAC/files/2326150/pipeline.txt)

Please let me know if there is any additional information that is required.
Thank you!

**Comment by anibalsolon** [comment]
Hi @Salonijain27 

Could you please send us the complete log file? It is a "pypeline.log" file within your log folder, under a subject folder. Some problem might be happening before this error.

And please check if these files exist on your computer:
/usr/local/fsl/data/standard/tissuepriors/2mm/avg152T1_white_bin.nii.gz
/usr/local/fsl/data/standard/tissuepriors/2mm/avg152T1_gray_bin.nii.gz
/usr/local/fsl/data/standard/tissuepriors/2mm/avg152T1_csf_bin.nii.gz

**Comment by Salonijain27** [comment]
Hi @anibalsolon ,
I have the files that you have mentioned above. I have attached my log file below:
[pypeline.log](https://github.com/FCP-INDI/C-PAC/files/2329389/pypeline.log)
You were right, there is an error I have before the above mentioned one. The error I get is :
```
180827-18:37:50,52 workflow INFO:
	 Executing node std_dev_1.b0 in dir: /tmp/resting_preproc_0025026_session_1/_scan_func-1/std_dev_1
180827-18:37:50,89 workflow ERROR:
	 [u'Node std_dev_1.b0 failed to run on host saloni-ubuntu.']
180827-18:37:50,90 workflow INFO:
	 Saving crash info to /home/saloni/NYU/crash_log/crash-20180827-183750-saloni-std_dev_1.b0-24624f35-f07d-46dc-b0aa-c7a958f845d5.pklz
180827-18:37:50,90 workflow INFO:
	 Traceback (most recent call last):
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1029, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 194, in _run_interface
    out = function_handle(**args)
  File "<string>", line 24, in gen_std_dev
  File "/home/saloni/miniconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'3dTstat', u'-stdev', u'-mask', u'/tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/rest_calc_tshift_resample_volreg_mask.nii.gz', u'-prefix', u'/tmp/resting_preproc_0025026_session_1/_scan_func-1/std_dev_1/std_dev.nii.gz', u'/tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_normalize/rest_calc_tshift_resample_volreg_calc_maths.img']' returned non-zero exit status 1
```
Thank you!

**Comment by Salonijain27** [comment]
Hi @anibalsolon ,
I made the changes in the pipeline and ran the code for pre-processing again. I get the following error :
```
180829-01:34:43,269 workflow INFO:
	 Executing node process_outputs_49 in dir: /tmp/resting_preproc_0025025_session_1/process_outputs_49
180829-01:34:43,320 workflow ERROR:
	 [u'Node WM_mask failed to run on host saloni-ubuntu.']
180829-01:34:43,410 workflow INFO:
	 Saving crash info to /home/saloni/NYU/crash_log/crash-20180829-013443-saloni-WM_mask-9984ca3e-a65c-4e32-9681-5667dc3d8ce7.pklz
180829-01:34:43,410 workflow INFO:
	 Traceback (most recent call last):
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in run
    self._get_inputs()
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 467, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 223, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 83, in validate
    validated_value = super(BaseFile, self).validate(object, name, value)
  File "/home/saloni/.local/lib/python2.7/site-packages/traits/trait_types.py", line 411, in validate
    self.error( object, name, value )
  File "/home/saloni/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
TraitError: The 'in_file' trait of a MultiImageMathsInput instance must be an existing file name, but a value of None <type 'NoneType'> was specified.
Error setting node input:
Node: WM_mask
input: in_file
results_file: /tmp/resting_preproc_0025025_session_1/seg_preproc_0/segment/result_segment.pklz
value: None
```
I have attached the pipeline.log file below. 
[pypeline.log](https://github.com/FCP-INDI/C-PAC/files/2333193/pypeline.log)

I also ran the following line :
```
3dTstat -stdev -mask /tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/rest_calc_tshift_resample_volreg_mask.nii.gz -prefix /tmp/resting_preproc_0025026_session_1/_scan_func-1/std_dev_1/std_dev.nii.gz /tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_normalize/rest_calc_tshift_resample_volreg_calc_maths.img
```
and got this output :
```
++ 3dTstat: AFNI version=AFNI_18.2.12 (Aug 17 2018) [64-bit]
++ Authored by: KR Hammett & RW Cox
** ERROR (nifti_image_read): failed to find header file for '/tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/rest_calc_tshift_resample_volreg_mask.nii.gz'
** FATAL ERROR: Cannot open mask dataset!
** Program compile date = Aug 17 2018
```

**Comment by Salonijain27** [comment]
Hi @anibalsolon ,
I have the files that you have mentioned above. I have attached my log file below:
[pypeline.log](https://github.com/FCP-INDI/C-PAC/files/2329389/pypeline.log)
You were right, there is an error I have before the above mentioned one. The error I get is :
```
180827-18:37:50,52 workflow INFO:
	 Executing node std_dev_1.b0 in dir: /tmp/resting_preproc_0025026_session_1/_scan_func-1/std_dev_1
180827-18:37:50,89 workflow ERROR:
	 [u'Node std_dev_1.b0 failed to run on host saloni-ubuntu.']
180827-18:37:50,90 workflow INFO:
	 Saving crash info to /home/saloni/NYU/crash_log/crash-20180827-183750-saloni-std_dev_1.b0-24624f35-f07d-46dc-b0aa-c7a958f845d5.pklz
180827-18:37:50,90 workflow INFO:
	 Traceback (most recent call last):
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1029, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/saloni/.local/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 194, in _run_interface
    out = function_handle(**args)
  File "<string>", line 24, in gen_std_dev
  File "/home/saloni/miniconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'3dTstat', u'-stdev', u'-mask', u'/tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/rest_calc_tshift_resample_volreg_mask.nii.gz', u'-prefix', u'/tmp/resting_preproc_0025026_session_1/_scan_func-1/std_dev_1/std_dev.nii.gz', u'/tmp/resting_preproc_0025026_session_1/func_preproc_automask_0/_scan_func-1/func_normalize/rest_calc_tshift_resample_volreg_calc_maths.img']' returned non-zero exit status 1
```
Thank you!

**Comment by nrajamani3** [comment]
Hi Salonijain27, this is just a thought to help you with this issue - could you take a look at your FSL data directory to check whether the CSF, WM and GM files are present and not corrupt? I was able to reproduce this error, but not with the CSF file - instead it was a missing input for 3 mm resolution symmetric_brain file. I solved that error by changing the resolution to 2mm, so I'm wondering if something similar is the problem with yours and if you can then solve it.

**Comment by Salonijain27** [comment]
Hi @nrajamani3,
Thank you so much for replying to my query! In response to you suggestions I checked the things you had requested :

- I have the CSF, WM and GM files. They are not corrupted. 
- I already using the resolution_for_anat = 2mm. I tried changing the resolution but I am still getting the same error.
Thank you!

**Comment by anibalsolon** [comment]
Hi @Salonijain27 ,

this is a strange behavior, we are trying to understand and debug it. Meanwhile, may I please ask you to wipe the C-PAC directories and try to execute the pipeline again?

```
rm -rF /home/saloni/NYU/crash_log/*
rm -rF /home/saloni/NYU/results/all_new/*
rm -rF /home/saloni/NYU/logs/*
rm -rF /tmp/resting_preproc*
```

**Comment by Salonijain27** [comment]
Hi  @anibalsolon ,
Thank you so much! I also wiped the C-PAC directories and executed the pipeline again and I obtained the same errors.

**Comment by nrajamani3** [comment]
@Salonijain27 can you look for the report folder in your working directory - each node that is executed will be present in the working directory and opening that would show you the report.rst file. It gives us the inputs, the path to the inputs and other information - you could also do this to debug the problems.
