### ISSUE TITLE
Conda install pip failed!

### ISSUE THREAD

**Issue by poppintiger** [FCP-INDI/C-PAC#845]
When I install C-PAC by running “sudo ./cpac_install.sh -r”， it pop up this following error. Dose any one know how to fix it?

[ Tue Oct 23 17:33:49 CST 2018 ] : C-PAC system dependencies are already installed, do not need to be re-installed.
[ Tue Oct 23 17:33:49 CST 2018 ] Installing miniconda!
ERROR: File or directory already exists: /usr/local/bin/miniconda
[ Tue Oct 23 17:33:49 CST 2018 ] Miniconda installation failed!
Error: prefix already exists: /usr/local/bin/miniconda/envs/cpac
discarding /usr/local/bin/miniconda/bin from PATH
prepending /usr/local/bin/miniconda/envs/cpac/bin to PATH
Fetching package metadata: .....
Solving package specifications: ^[[B

^[[A^H^HAn unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 329, in install
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 733, in solve
    minimal_hint=minimal_hint)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 504, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: numpy-base-1.14.3-py35h0ea5e3f_1.tar.bz2 MatchSpec(u'blas * openblas')
[ Tue Oct 23 18:52:21 CST 2018 ] Conda install pip failed!

**Comment by anibalsolon** [comment]
Hi @poppintiger 

It looks like you already have C-PAC installed on your machine!
Which "miniconda" file have you removed?

You can try to reinstall C-PAC using:
```
source activate cpac
pip install git+git://github.com/FCP-INDI/C-PAC.git
```

Please let us know about your progress!

**Comment by poppintiger** [comment]
Hi,
    Thank you for your reply !
     I have already degraded my ubuntu system from 16 to 14, but when I install by running this command:
      It still show some errors:
said: I  need  apt-get -f install to correct the errors   and:
[ 2018年 11月 05日 星期一 13:38:09 CST ] apt-get failed to install packages: cmake git graphviz graphviz-dev gsl-bin libexpat1-dev libgiftiio-dev libglib2.0-dev libglu1-mesa-dev libjpeg-progs libxml2-dev libxext-dev libxft-dev libxi-dev libxmu-headers libxmu-dev libxpm-dev libxslt1-dev mesa-common-dev mesa-utils netpbm build-essential xvfb libgl1-mesa-dri tcsh zlib1g-dev m4 libmotif-dev libxp-dev libgsl0-dev

[ 2018年 11月 05日 星期一 13:38:09 CST ] apt-get failed to install packages: cmake git graphviz graphviz-dev gsl-bin libexpat1-dev libgiftiio-dev libglib2.0-dev libglu1-mesa-dev libjpeg-progs libxml2-dev libxext-dev libxft-dev libxi-dev libxmu-headers libxmu-dev libxpm-dev libxslt1-dev mesa-common-dev mesa-utils netpbm build-essential xvfb libgl1-mesa-dri tcsh zlib1g-dev m4 libmotif-dev libxp-dev libgsl0-dev


Cannot fully install C-PAC system dependencies.

**Comment by poppintiger** [comment]
[ 2018年 11月 05日 星期一 14:00:57 CST ] : C-PAC system dependencies not fully installed.
Python dependencies cannot be installed unless system-level dependencies are installed first.
Have your system administrator install system-level dependencies as root.

**Comment by poppintiger** [comment]
Hi , I followed your method by running the code:
source activate cpac pip install git+git://github.com/FCP-INDI/C-PAC.git

Unfortunately, I cannot import the package:
When I import directly in capc environment:

(cpac)lsx@lsx-Vostro:$ import CPAC.timeseries.timeseries_analysis as t
import-im6.q16: not authorized `t' @ error/constitute.c/WriteImage/1037.

When I came into python environment, it was still not working. 

(cpac)lsx@lsx-Vostro:$ python
Python 2.7.15 |Anaconda, Inc.| (default, Oct 23 2018, 18:31:10)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

             from CPAC.anat_preproc import create_anat_preproc
            Traceback (most recent call last):
            File "", line 1, in
            ImportError: No module named CPAC.anat_preproc

So, how can I solve it?

**Comment by anibalsolon** [comment]
Hi @poppintiger do you have any updates in this matter? sorry for dropping the ball in this one.
