### ISSUE TITLE
CPAC container crash

### ISSUE THREAD

**Issue by stealthybif** [FCP-INDI/C-PAC#846]
I'm running into similar issues posted by ccraddock earlier #844  when running the latest cpac container. In addition to their crash log, I'm experiencing the following crash messages as well:

Traceback (most recent call last):
  File "/usr/local/bin/nipypecli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nipype/scripts/cli.py", line 108, in show
    pkl_data = loadpkl(pklz_file)
  File "/usr/local/lib/python2.7/dist-packages/nipype/utils/filemanip.py", line 668, in loadpkl
    raise e
KeyError: '{'

Traceback (most recent call last):
  File "/usr/local/bin/nipypecli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nipype/scripts/cli.py", line 94, in crash
    display_crash_file(crashfile, rerun, debug, dir)
  File "/usr/local/lib/python2.7/dist-packages/nipype/scripts/crash_files.py", line 51, in display_crash_file
    crash_data = loadcrash(crashfile)
  File "/usr/local/lib/python2.7/dist-packages/nipype/utils/filemanip.py", line 632, in loadcrash
    return loadpkl(infile, versioning=True)
  File "/usr/local/lib/python2.7/dist-packages/nipype/utils/filemanip.py", line 683, in loadpkl
    raise e
ImportError: No module named function

Any recommendations to resolve?

**Comment by anibalsolon** [comment]
Hi @stealthybif 

About ccraddock problem, you can pull the new Docker image and try to run C-PAC again:
```
docker pull childmind/c-pac:latest
```

About your local error, it happens because you do not have C-PAC installed in your local machine. The error is generated in the Docker environment, which has C-PAC installed. You can open the crash folder in the terminal and run:
```
docker run -it -v `pwd`:/current_path -w "/current_path" --entrypoint="nipypecli" childmind/c-pac crash MYCRASHFILE.pklz
```

Also, we are going to offer .txt files when C-PAC crashes on Docker, since the user is not supposed to have C-PAC installed in the local machine.

Please let us know if it works!

**Comment by stealthybif** [comment]
Hi,

Thank you that was helpful in getting a more detailed crash report. 

Let me know if it's better to redirect this to the google forum instead: I am now getting KeyErrors for 'TR', 'acquisition', 'reference', etc... It seems that those fields are not auto-generated in the data yaml. Is it expected to modify the yaml file manually to fill in the correct values?

Thank you

**Comment by anibalsolon** [comment]
Hi @stealthybif 

Could you please provide us more information about how you generated the data config?
- Are you generating it locally?
- Using the GUI or command line?
- For a BIDS dataset or a custom format dataset?

Thank you

**Comment by stealthybif** [comment]
Hi @anibalsolon 

Yes of course.  
The data config is not being generated locally. 
It is being generated on command line by:
docker run -i --rm -v /home/ubuntu/bids:/bids_dataset -v /home/ubuntu/cpac2:/outputs -v /tmp:/scratch childmind/c-pac:latest /bids_dataset /outputs participant

And this is for a BIDS dataset generated from the heudiconv container.

Aside from that, I've been following the #844  issue and I think they are similar if not the same thing. 

I'm following the instructions for running the default pipeline config found here: http://fcp-indi.github.io/docs/user/running.html

Thanks!

**Comment by anibalsolon** [comment]
Hi @stealthybif 

Thank you for the info! We've updated the docker image with the fix, so a `docker pull childmind/c-pac:latest` will sync your local version with the fixed one.

Please let us know if you have further questions or problems!

**Comment by anibalsolon** [comment]
Hi @stealthybif

Let us know if you have further problems by opening a new issue :D
