### ISSUE TITLE
Key error when I toggle run* fields in pipeline config

### ISSUE THREAD

**Issue by dowd-a** [FCP-INDI/C-PAC#889]
I've been trying to configure the pipeline to only run specific types of processing (anatomical only, preprocessing only, no nuisance regression, etc.). When I just set all the run* fields (runALFF, runBBReg, runEPI_DistCorr, etc.) in the pipeline config file to [0], I get this key error.

`181204-16:20:05,502 nipype.workflow INFO:
	 Selected Slice Timing pattern ['Use NIFTI Header']
181204-16:20:05,514 nipype.workflow INFO:
	  finished connecting slice timing pattern
No handlers could be found for logger "workflow"
Traceback (most recent call last):
  File "/code/run.py", line 392, in <module>
    plugin='MultiProc', plugin_args=plugin_args)
  File "/code/CPAC/pipeline/cpac_runner.py", line 487, in run
    p_name, plugin, plugin_args)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 3354, in prep_workflow
    create_qc_workflow(workflow, c, strat_list, Outputs.qc)
  File "/code/CPAC/qc/pipeline.py", line 46, in create_qc_workflow
    func_to_anat_xfm, xfm_file = strat['functional_to_anat_linear_xfm']
  File "/code/CPAC/utils/strategy.py", line 57, in __getitem__
    return self.resource_pool[resource_key]
KeyError: 'functional_to_anat_linear_xfm'
`

**Comment by sgiavasis** [comment]
Hi @dowd-a ,

This looks to be a simple case of rigidity in the pipeline building, similar to the issues with running anat only. I'm going to push these fixes into this release. Thanks for all of the testing so far.

Steve

**Comment by dowd-a** [comment]
Okay, thanks for looking into it.
