### ISSUE TITLE
Error with bids validator

### ISSUE THREAD

**Issue by dowd-a** [FCP-INDI/C-PAC#890]
Every time I run C-PAC I get this syntax error when the bids validator is run. I'm not sure what's causing it, and it doesn't seem to affect the pipeline since it is there even when C-PAC executes cleanly. I just thought I'd let you know in case it's a bigger issue.

Running BIDS validator
/usr/lib/node_modules/bids-validator/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/bids-validator/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Also, when I run C-PAC for a single participant, does the bids validator check the entire data set or just that participant?

**Comment by sgiavasis** [comment]
This has been resolved and the fix will be in C-PAC v1.4.0.
