### ISSUE TITLE
Import CPAC error 

### ISSUE THREAD

**Issue by Sandyaoh** [FCP-INDI/C-PAC#940]
Hi, I've been trying for several days to install CPAC

I get this error, when i do import CPAC after having install CPAC.

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/astrid/miniconda/lib/python2.7/site-packages/CPAC/__init__.py", line 21, in <module>
    import anat_preproc, \
  File "/home/astrid/miniconda/lib/python2.7/site-packages/CPAC/anat_preproc/__init__.py", line 3, in <module>
    from CPAC.anat_preproc.anat_preproc import create_anat_preproc
  File "/home/astrid/miniconda/lib/python2.7/site-packages/CPAC/anat_preproc/anat_preproc.py", line 3, in <module>
    from nipype.interfaces import afni
  File "/home/astrid/.local/lib/python2.7/site-packages/nipype/__init__.py", line 12, in <module>
    from .utils.config import NipypeConfig
  File "/home/astrid/.local/lib/python2.7/site-packages/nipype/utils/__init__.py", line 4, in <module>
    from .config import NUMPY_MMAP
  File "/home/astrid/.local/lib/python2.7/site-packages/nipype/utils/config.py", line 23, in <module>
    from builtins import bytes, str, object, open
ImportError: No module named builtins 

```
By the way, when using```python setup.py install ```  I got this at the beginning:

    /home/user/miniconda/envs/cpac/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /home/astrid/miniconda/envs/cpac/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
     warnings.warn(msg)
    Warning: No module named anat_preproc/bin/sh: 1: svnversion: not found
    /bin/sh: 1: hg: not found
    running install
    ...

Thanks in advance

**Comment by nrajamani3** [comment]
Hi @Sandyaoh : few points: in order to prevent such errors, it would be great if you could use our docker container. If you have issues with sudo permissions, singularity container can also be used. As to address your issue - have you installed builtins? if you have not, please install it by typing                    $pip install builtins 
After this, you can reinstall CPAC, and try to import it.
Please let us know how you progress with this.

**Comment by Sandyaoh** [comment]
Ok, I'm installing Docker

Meanwhile when using $pip install builtins it shows:

Collecting builtins
Could not find a version that satisfies the requirement builtins (from versions: )
No matching distribution found for builtins

 You are using pip version 9.0.1, however version 19.0.3 is available.
 You should consider upgrading via the 'pip install --upgrade pip' command.

But when I upgraded pip before it stopped working, so I kept this version

**Comment by nrajamani3** [comment]
Could you try pip install future and see if that fixes it?

**Comment by Sandyaoh** [comment]
Already tried. When using $pip install future show that  ```Requirement already satisfied: future in /usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages ```

But I got he same error doing again ```Import CPAC``` on python

**Comment by Sandyaoh** [comment]
Already tried, when using $pip install future it shows:  ```Requirement already satisfied: future in /usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages ```

And I stiil got the same error using ```Import CPAC``` on python

**Comment by anibalsolon** [comment]
Hi @Sandyaoh 

Sorry to hear you are having problems!

It looks like you have two Minicondas installed in your system. Could you please check this divergence for us?
From the first stacktrace, I see this one:
```
/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages
```

and in the last comment, you have:
```
/home/astrid/miniconda/lib/python2.7/site-packages
```

I would guess that
```
/home/astrid/miniconda/envs/cpac/bin/pip install --upgrade future
```
might solve your issue, but to avoid confusion I would recommend to stick with one of the Minicondas, and delete the other one.

**Comment by anibalsolon** [comment]
Hi @Sandyaoh

Do you have an update for this issue? Please let us know!

**Comment by sgiavasis** [comment]
Closing due to inactivity- @Sandyaoh please do reach out if you still need assistance.
