### ISSUE TITLE
Melodic crash

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#941]
Trying to process roughly 120 functional datasets, received similar errors on 64. Looks like to problem is that dimensions of the various arrays in the line:

motionICs = np.squeeze(np.array(np.where((proj > 0) + (csfFract > thr_csf) + (HFC > thr_HFC))))

____
190322-00:25:10,152 nipype.workflow ERROR:
         Node aroma_wf.b5 failed to run on host c262-173.hikari.tacc.utexas.edu.
190322-00:25:10,153 nipype.workflow ERROR:
         Saving crash info to /outputs/crash/crash-20190322-002510-craddock-aroma_wf.b5-c937af2f-faa5-4d67-9471-aeeeb12fe098.pklz
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1033, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 970, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
ICA_AROMA.py -den nonaggr -i /scratch/working/resting_preproc_sub-ang1017_ses-1/apply_ants_warp_leaf_node_to_standard_0/_scan_rest_run-01/apply_ants_warp/sub-ang1017_ses-1_task-rest_run-01_bold_calc_tshift_resample_volreg_calc_maths_antswarp.nii.gz -m /scratch/working/resting_preproc_sub-ang1017_ses-1/create_aroma_0/_scan_rest_run-01/bet_aroma/sub-ang1017_ses-1_task-rest_run-01_bold_calc_tshift_resample_volreg_calc_maths_antswarp_brain_mask.nii.gz -mc /scratch/working/resting_preproc_sub-ang1017_ses-1/create_aroma_0/_scan_rest_run-01/par_mcflirt/sub-ang1017_ses-1_task-rest_run-01_bold_calc_tshift_resample_volreg_calc_maths_antswarp_mcf.nii.gz.par -o /scratch/working/resting_preproc_sub-ang1017_ses-1/create_aroma_0
Standard output:

------------------------------- RUNNING ICA-AROMA -------------------------------
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' ---------------

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Standard error:
Traceback (most recent call last):
  File "/opt/ICA-AROMA/ICA_AROMA.py", line 211, in <module>
    motionICs = aromafunc.classification(outDir, maxRPcorr, edgeFract, HFC, csfFract)
  File "/opt/ICA-AROMA/ICA_AROMA_functions.py", line 496, in classification
    motionICs = np.squeeze(np.array(np.where((proj > 0) + (csfFract > thr_csf) + (HFC > thr_HFC))))
ValueError: operands could not be broadcast together with shapes (48,) (50,)
Return code: 1

**Comment by sgiavasis** [comment]
Hi @ccraddock,

Thanks for bringing this up- we'll try to reproduce it and get back to you as soon as we can.

Anything specific about the data, or the 64 that crashed, that would be good for us to know?

Best,
Steve
