### ISSUE TITLE
Unable to save config yaml

### ISSUE THREAD

**Issue by mattcieslak** [FCP-INDI/C-PAC#963]
After editing the nuisance regression options in the GUI there is an error when trying to save the updated pipeline.  I'm running the gui from ubuntu 16.04 x86_64 through docker via:

```
docker run --rm -ti --env="DISPLAY" -v /home/mcieslak/.Xauthority:/root/.Xauthority:rw --net=host -v /home/mcieslak/Downloads/DSCSDSI:/BIDS -v /tmp:/scratch -v /home/mcieslak:/work -w="/work" fcpindi/c-pac:latest /BIDS /scratch gui

```

The first error is 

```
(run.py:1): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
Traceback (most recent call last):
  File "/code/CPAC/GUI/interface/windows/main_window.py", line 407, in NewItem
    MainFrame(self, "load", path=p.resource_filename('CPAC', 'resources/configs/pipeline_config_template.yml'))
  File "/code/CPAC/GUI/interface/windows/config_window.py", line 281, in __init__
    self.load()
  File "/code/CPAC/GUI/interface/windows/config_window.py", line 368, in load
    ctrl.set_value(val)
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 1018, in set_value
    self.ctrl.update(value)
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 897, in update
    self.render()
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 991, in render
    description = wx.StaticText(self.scroll, wx.ID_ANY, selectors_description)
  File "/usr/local/miniconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_controls.py", line 997, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 61: ordinal not in range(128)
Traceback (most recent call last):
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 991, in render
    description = wx.StaticText(self.scroll, wx.ID_ANY, selectors_description)
  File "/usr/local/miniconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_controls.py", line 997, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 61: ordinal not in range(128)
Traceback (most recent call last):
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 991, in render
    description = wx.StaticText(self.scroll, wx.ID_ANY, selectors_description)
  File "/usr/local/miniconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_controls.py", line 997, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 61: ordinal not in range(128)

```
Followed by

```
Traceback (most recent call last):
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 991, in render
    description = wx.StaticText(self.scroll, wx.ID_ANY, selectors_description)
  File "/usr/local/miniconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_controls.py", line 997, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 61: ordinal not in range(128)
Traceback (most recent call last):
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 991, in render
    description = wx.StaticText(self.scroll, wx.ID_ANY, selectors_description)
  File "/usr/local/miniconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_controls.py", line 997, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 61: ordinal not in range(128)
Traceback (most recent call last):
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 937, in save_regressor
    sel = editor.compile_selector()
  File "/code/CPAC/GUI/interface/pages/nuisance.py", line 792, in compile_selector
    selector['GreyMatter'].update(self.compile_selector_summary(self.data_controls['GreyMatter']))
KeyError: 'GreyMatter'

```

The result is the default options are written to a yaml file with none of the changes made in the gui present.

**Comment by anibalsolon** [comment]
Hi @mattcieslak 

Thank you for reporting it! This error has been fixed and it will be available in our next release.
Meanwhile, you can manually edit the pipeline config file with your regressors and we can help you with that if you have any questions.

**Comment by mattcieslak** [comment]
We manually edited the config and it's running. Thanks!
