### ISSUE TITLE
minimal example with test data

### ISSUE THREAD

**Issue by jdkent** [FCP-INDI/C-PAC#964]
Hi!

I was trying to test out a minimal bids dataset ([linked here](https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/57f32a429ad5a101f977eb75)) using the  most recent version of CPAC (on singularity) with configuration file named [mah_pipes.yml](https://github.com/NeuroimagingUIowa/cpacAdventures/blob/1a16fd1c04601fbe1bbe7f56cfc29552b6f3004d/mah_pipes.yml). 

I got this message in the crash file: 
```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nipypecli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/scripts/cli.py", line 94, in crash
    display_crash_file(crashfile, rerun, debug, dir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/scripts/crash_files.py", line 51, in display_crash_file
    crash_data = loadcrash(crashfile)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 632, in loadcrash
    return loadpkl(infile, versioning=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 683, in loadpkl
    raise e
traits.trait_errors.TraitError: The trait 'ort' of a TProjectInputSpec instance is an existing file name, but the path  '/scratch/working/resting_preproc_sub-01_ses-1/nuisance_0_0/_scan_mixedgamblestask_run-02/_selector_/build_nuisance_regressors/nuisance_regressors.1D' does not exist.
```

Perhaps there are not enough volumes in the test dataset or perhaps my config file is mis-specified? 

Is there a recommended starter dataset to play with?

Thanks for all your work on this, people want to use this at the University of Iowa, but they are waiting on me to figure it out.

P.S. [Here is a readme](https://github.com/NeuroimagingUIowa/cpacAdventures/blob/1a16fd1c04601fbe1bbe7f56cfc29552b6f3004d/README.md) outlining the things I did to try to get it working.

**Comment by sgiavasis** [comment]
Hi @jdkent,

Good to hear from you! We're looking into this right now- we recently revamped our entire nuisance regression suite and we'll find out if this is some minor issue or bug or something else.

I really dig your C-PAC adventures, by the way.

Best,
Steve

**Comment by anibalsolon** [comment]
Hi @jdkent 

Thank you for reaching out, the input from your adventures are really helpful to improve C-PAC!

We've updated the regressors definition in our last version, and I am working right now to also update the GUI to output it in the right format. It should be released this week.

We have the definition in our documentation, and how to convert the old format to the new one:
http://fcp-indi.github.io/docs/user/nuisance.html

Please, let us know how it goes!
