### ISSUE TITLE
Singularity hub container doesn't work

### ISSUE THREAD

**Issue by mnarayan** [FCP-INDI/C-PAC#980]
The latest singularity container from singularity hub fails to run. 

After doing `singularity pull shub://FCP-INDI/C-PAC`
Attempting to run the container results in the following error, despite having cleaned the environment variables. 

```
Traceback (most recent call last):
  File "/code/run.py", line 14, in <module>
    from CPAC.utils.yaml_template import create_yaml_from_template
  File "/code/CPAC/__init__.py", line 21, in <module>
    import anat_preproc, \
  File "/code/CPAC/anat_preproc/__init__.py", line 3, in <module>
    from CPAC.anat_preproc.anat_preproc import create_anat_preproc
  File "/code/CPAC/anat_preproc/anat_preproc.py", line 3, in <module>
    from nipype.interfaces import afni
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/__init__.py", line 12, in <module>
    from .utils.config import NipypeConfig
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/utils/__init__.py", line 4, in <module>
    from .config import NUMPY_MMAP
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/utils/config.py", line 20, in <module>
    import configparser
  File "/usr/local/miniconda/lib/python2.7/site-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ImportError: No module named configparser
```

**Comment by anibalsolon** [comment]
Hi @mnarayan 

Thank you for reaching out with this problem. We are trying to get a hold on SingularityHub, since the way it works is not too streamlined.

Could you please try to build the image yourself, to see if the problem remains the same?

Meanwhile, I will take a look at the Singularity Hub image.

Thank you!

**Comment by anibalsolon** [comment]
@mnarayan and could you send us the full singularity run command? Thanks!

**Comment by sgiavasis** [comment]
Closing due to inactivity. @mnarayan, if you still need assistance, please reach out.
