### ISSUE TITLE
Less timepoints than ROIs- warning/message instead of crash

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#996]
A "check_timeseries" crash results if the number of time points is smaller than the number of ROIs in an ROI file:

> Node: resting_preproc_4275075_1.temporal_regression_sca_0.check_timeseries
> Working directory: /output/working/resting_preproc_4275075_1/temporal_regression_sca_0/_scan_rest_acq-2_run-1/_selector_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/_target_angle_deg_90/_mask_rois_3mm_mask_file_..cpac_templates..rois_3mm.nii.gz/check_timeseries
> 
> 
> Node inputs:
> 
> function_str = def check_ts(in_file):
>     import numpy as np
>     try:
>         timepoints, rois = np.loadtxt(in_file).shape
>     except ValueError:
>         timepoints = np.loadtxt(in_file).shape[0]
>         rois = 1	
>     if rois > timepoints:
>         message = ('\n\n\n****The number of timepoints (' + str(timepoints)
>                    + ') is smaller than the number of ROIs to run ('
>                    + str(rois) + ') - therefore the GLM is'
>                    + ' underspecified and can\'t run.****\n\n\n')
>         print(message)
>         raise Exception(message)
>     else:
>         return in_file
> 
> in_file = /output/working/resting_preproc_4275075_1/roi_timeseries_for_mult_reg_0/_scan_rest_acq-2_run-1/_selector_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/_target_angle_deg_90/_mask_rois_3mm_mask_file_..cpac_templates..rois_3mm.nii.gz/clean_roi_csv/roi_stats.csv
> 
> 
> 
> Traceback: 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
>     result['result'] = node.run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
>     out = function_handle(**args)
>   File "<string>", line 14, in check_ts
> Exception: 
> 
> 
> ****The number of timepoints (120) is smaller than the number of ROIs to run (161) - therefore the GLM is underspecified and can't run.****

We should make it so that this either writes to the logger.warn() log, or maybe print out a file explaining this, instead of generating crash files.

**Comment by anibalsolon** [comment]
Possible problem: by setting as a warning, it will crash in fsl.GLM interface anyway, producing a more confusing crash file.
