### ISSUE TITLE
SegFault Nuisance Regression CPAC v1.4.1

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#998]
This is Ubuntu 16.04 and CPAC 1.4.1
I am receiving these crash files:

```
(cpac)jlee38@rsmachine:~/EXECUTE/crsh$ nipypecli crash crash-20190519-100350-jlee38-nuisance_regression.a0.b0-f1d0ad89-3ae5-49f1-b022-0f645f3bb40d.pklz


File: /home/jlee38/EXECUTE/crsh/crash-20190519-100350-jlee38-nuisance_regression.a0.b0-f1d0ad89-3ae5-49f1-b022-0f645f3bb40d.pklz
Node: resting_preproc_109678-100_ses-1.nuisance_0_0.nuisance_regression
Working directory: /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/nuisance_regression


Node inputs:

TR = <undefined>
args = <undefined>
automask = <undefined>
bandpass = <undefined>
blur = <undefined>
cenmode = KILL
censor = /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/find_offending_time_points/censors.tsv
censortr = <undefined>
concat = <undefined>
dsort = <undefined>
environ = {}
in_file = /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/nuisance_regression/denoised_func_data_nonaggr_antswarp.nii.gz
mask = /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/funcf_calc_tshift_resample_volreg_mask.nii.gz
noblock = <undefined>
norm = False
num_threads = 1
ort = /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/build_nuisance_regressors/nuisance_regressors.1D
out_file = residuals.nii.gz
outputtype = NIFTI_GZ
polort = 0
stopband = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1033, in _run_interface
    self.raise_exception(runtime)
  File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 970, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
3dTproject -input /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/nuisance_regression/denoised_func_data_nonaggr_antswarp.nii.gz -cenmode KILL -censor /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/find_offending_time_points/censors.tsv -mask /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/funcf_calc_tshift_resample_volreg_mask.nii.gz -ort /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/build_nuisance_regressors/nuisance_regressors.1D -polort 0 -prefix residuals.nii.gz
Standard output:
** Memory usage: chunks=306 bytes=98960
Standard error:
++ 3dTproject: AFNI version=AFNI_19.1.08 (May 10 2019) [64-bit]
++ Authored by: Cox the Algebraic (Linear)
** AFNI converts NIFTI_datatype=64 (FLOAT64) in file /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/nuisance_regression/denoised_func_data_nonaggr_antswarp.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.

Fatal Signal 11 (SIGSEGV) received
   mri_read_1D
  3dTproject
 Bottom of Debug Stack
** Command line was:
3dTproject -input /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/nuisance_regression/denoised_func_data_nonaggr_antswarp.nii.gz -cenmode KILL -censor /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/find_offending_time_points/censors.tsv -mask /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/funcf_calc_tshift_resample_volreg_mask.nii.gz -ort /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/build_nuisance_regressors/nuisance_regressors.1D -polort 0 -prefix residuals.nii.gz
** AFNI version = AFNI_19.1.08  Compile date = May 10 2019
** [[Precompiled binary linux_openmp_64: May 10 2019]]
** Program Death **
** If you report this crash to the AFNI message board,
** please copy the error messages EXACTLY, and give
** the command line you used to run the program, and
** any other information needed to repeat the problem.
** You may later be asked to upload data to help debug.
** Crash log is appended to file /home/jlee38/.afni.crashlog
Return code: 1
```

Pipeline Attached:
[REVISIONpipeline_config_proc_pt25_ICA_AROMA.txt](https://github.com/FCP-INDI/C-PAC/files/3199134/REVISIONpipeline_config_proc_pt25_ICA_AROMA.txt)

**Comment by sgiavasis** [comment]
Hi @nimzodisaster,

What happens when you run the command manually, from the command line? This one specifically:

> 3dTproject -input /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/nuisance_regression/denoised_func_data_nonaggr_antswarp.nii.gz -cenmode KILL -censor /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/find_offending_time_points/censors.tsv -mask /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/func_preproc_automask_0/_scan_func-1/func_get_brain_mask/funcf_calc_tshift_resample_volreg_mask.nii.gz -ort /home/jlee38/EXECUTE/wrk/resting_preproc_109678-100_ses-1/nuisance_0_0/_scan_func-1/_selector_CSF-2mmE-M_M-SDB_BP-B0.008-T0.08_C-K-0+0-FD-P0.25/build_nuisance_regressors/nuisance_regressors.1D -polort 0 -prefix residuals.nii.gz
